create or replace view "public"."v_ust_facility" as
 SELECT a.ust_control_id,
    a.facility_id AS "FacilityID",
    a.facility_name AS "FacilityName",
    ot.owner_type AS "OwnerType",
    ft.facility_type AS "FacilityType1",
    ft2.facility_type AS "FacilityType2",
    a.facility_address1 AS "FacilityAddress1",
    a.facility_address2 AS "FacilityAddress2",
    a.facility_city AS "FacilityCity",
    a.facility_county AS "FacilityCounty",
    a.facility_zip_code AS "FacilityZipCode",
    a.facility_state AS "FacilityState",
    a.facility_epa_region AS "FacilityEPARegion",
    a.facility_tribal_site AS "FacilityTribalSite",
    a.facility_tribe AS "FacilityTribe",
    a.facility_latitude AS "FacilityLatitude",
    a.facility_longitude AS "FacilityLongitude",
    cs.coordinate_source AS "FacilityCoordinateSource",
    a.facility_owner_company_name AS "FacilityOwnerCompanyName",
    a.facility_operator_company_name AS "FacilityOperatorCompanyName",
    a.financial_responsibility_obtained AS "FinancialResponsibilityObtained",
    a.financial_responsibility_bond_rating_test AS "FinancialResponsibilityBondRatingTest",
    a.financial_responsibility_commercial_insurance AS "FinancialResponsibilityCommercialInsurance",
    a.financial_responsibility_guarantee AS "FinancialResponsibilityGuarantee",
    a.financial_responsibility_letter_of_credit AS "FinancialResponsibilityLetterOfCredit",
    a.financial_responsibility_local_government_financial_test AS "FinancialResponsibilityLocalGovernmentFinancialTest",
    a.financial_responsibility_risk_retention_group AS "FinancialResponsibilityRiskRetentionGroup",
    a.financial_responsibility_self_insurance_financial_test AS "FinancialResponsibilitySelfInsuranceFinancialTest",
    a.financial_responsibility_state_fund AS "FinancialResponsibilityStateFund",
    a.financial_responsibility_surety_bond AS "FinancialResponsibilitySuretyBond",
    a.financial_responsibility_trust_fund AS "FinancialResponsibilityTrustFund",
    a.financial_responsibility_other_method AS "FinancialResponsibilityOtherMethod",
    a.ust_reported_release AS "USTReportedRelease",
    a.associated_ust_release_id AS "AssociatedUSTReleaseID"
   FROM ((((ust_facility a
     LEFT JOIN owner_types ot ON ((a.owner_type_id = ot.owner_type_id)))
     LEFT JOIN coordinate_sources cs ON ((a.coordinate_source_id = cs.coordinate_source_id)))
     LEFT JOIN facility_types ft ON ((a.facility_type1 = ft.facility_type_id)))
     LEFT JOIN facility_types ft2 ON ((a.facility_type2 = ft2.facility_type_id)));