CREATE TABLE sd_release.erg_sd_release_clean_cui (
    "id" double precision  NULL ,
    "status" text  NULL ,
    "r1" text  NULL ,
    "date_rep" text  NULL ,
    "date_close" text  NULL ,
    "image" boolean  NULL ,
    "site_name" text  NULL ,
    "site_name_cui" boolean  NULL ,
    "resp_party" text  NULL ,
    "street" text  NULL ,
    "city" text  NULL ,
    "zip_code" text  NULL ,
    "county" text  NULL ,
    "latitude" double precision  NULL ,
    "longitude" double precision  NULL ,
    "township" text  NULL ,
    "range" text  NULL ,
    "section" text  NULL ,
    "secq1" text  NULL ,
    "acreage" double precision  NULL ,
    "instctrls" text  NULL ,
    "material" text  NULL ,
    "amount" double precision  NULL ,
    "units" text  NULL ,
    "spill_cat" text  NULL ,
    "site_type" text  NULL ,
    "proptype" text  NULL ,
    "sor_type" text  NULL ,
    "regulated" boolean  NULL ,
    "cause_type" text  NULL ,
    "atp_no" double precision  NULL ,
    "prcfnumber" text  NULL ,
    "ag_no" text  NULL ,
    "solidwaste" text  NULL ,
    "microroll" text  NULL ,
    "siteid" bigint  NULL );