select 'null as "' || element_name || '",' from lust_elements order by element_position ;

select * from "TN_LUST"."TN_LUST_template" ;


create view "TN_LUST".v_lust as
select
	"FacilityID",
	null as "TankIDAssociatedwithRelease",
	"LUSTID",
	null as "FederallyReportableRelease",
	"SiteName",
	"SiteAddress",
	"SiteAddress2",
	"SiteCity",
	"Zipcode",
	"County",
	"State",
	"EPARegion",
	null as "FacilityType",
	null as "TribalSite",
	null as "Tribe",
	null as "Latitude",
	null as "Longitude",
	null as "CoordinateSource",
	"LUSTStatus",
	"ReportedDate",
	null as "NFADate",
	null as "MediaImpactedSoil",
	null as "MediaImpactedGroundwater",
	null as "MediaImpactedSurfaceWater",
	"SubstanceReleased1",
	null as "QuantityReleased1",
	null as "Unit1",
	"SubstanceReleased2",
	null as "QuantityReleased2",
	null as "Unit2",
	"SubstanceReleased3",
	null as "QuantityReleased3",
	null as "Unit3",
	"SubstanceReleased4",
	null as "QuantityReleased4",
	null as "Unit4",
	"SubstanceReleased5",
	null as "QuantityReleased5",
	null as "Unit5",
	null as "SourceOfRelease1",
	null as "CauseOfRelease1",
	null as "SourceOfRelease2",
	null as "CauseOfRelease2",
	null as "SourceOfRelease3",
	null as "CauseOfRelease3",
	"HowReleaseDetected",
	null as "RemediationStrategy1",
	null as "RemediationStrategy1StartDate",
	null as "RemediationStrategy2",
	null as "RemediationStrategy2StartDate",
	null as "RemediationStrategy3",
	null as "RemediationStrategy3StartDate",
	null as "ClosedWithContamination",
	null as "NoFurtherActionLetterURL",
	null as "MilitaryDoDSite"
from "TN_LUST"."TN_LUST_template" ;

select * from "TN_LUST".v_lust order by "FacilityID", "LUSTID";