CREATE TABLE va_ust.erg_va_ust_clean_cui (
    "X" double precision  NULL ,
    "Y" double precision  NULL ,
    "OBJECTID" bigint  NULL ,
    "FAC_ID" bigint  NULL ,
    "CHANGED_BY" text  NULL ,
    "CHANGED_DATE" text  NULL ,
    "INSERTED_BY" text  NULL ,
    "INSERTED_DATE" text  NULL ,
    "VERIFIEDBY" text  NULL ,
    "VERIFYDATE" text  NULL ,
    "REFERENCE_POINT" text  NULL ,
    "FAC_ID_1" double precision  NULL ,
    "CEDS_FAC_ID" double precision  NULL ,
    "FAC_NAME" text  NULL ,
    "FAC_NAME_cui" boolean  NULL ,
    "FAC_TYPE" text  NULL ,
    "FAC_ADDR1" text  NULL ,
    "FAC_ADDR2" text  NULL ,
    "FAC_CITY" text  NULL ,
    "FAC_STATE" text  NULL ,
    "FAC_ZIP5" double precision  NULL ,
    "FAC_LOCATION" text  NULL ,
    "NAME" text  NULL ,
    "PARENT_REG_ALT_DESCRIPTION" text  NULL ,
    "FAC_ACTIVE_YN" text  NULL ,
    "FAC_FED_REG_YN" text  NULL ,
    "FAC_ACTIVE_UST" double precision  NULL ,
    "FAC_INACTIVE_UST" double precision  NULL ,
    "FAC_ACTIVE_AST" double precision  NULL ,
    "FAC_INACTIVE_AST" double precision  NULL ,
    "Lat" double precision  NULL ,
    "Lon" double precision  NULL ,
    "FAC_INSP_YEAR" double precision  NULL ,
    "FAC_RISK_RANK" text  NULL );