CREATE TABLE md_ust.erg_md_ust_clean_cui (
    "FacilityID" bigint  NULL ,
    "FacilityName" text  NULL ,
    "FacilityName_cui" boolean  NULL ,
    "OwnerType" double precision  NULL ,
    "FacilityType1" double precision  NULL ,
    "FacilityType2" double precision  NULL ,
    "FacilityAddress1" text  NULL ,
    "FacilityAddress2" double precision  NULL ,
    "FacilityCity" text  NULL ,
    "FacilityCounty" text  NULL ,
    "FacilityZipCode" bigint  NULL ,
    "FacilityState" text  NULL ,
    "FacilityEPARegion" bigint  NULL ,
    "FacilityTribalSite" double precision  NULL ,
    "FacilityTribe" double precision  NULL ,
    "FacilityLatitude" double precision  NULL ,
    "FacilityLongitude" double precision  NULL ,
    "FacilityCoordinateSource" double precision  NULL ,
    "FacilityOwnerCompanyName" text  NULL ,
    "FacilityOperatorCompanyName" double precision  NULL ,
    "FinancialResponsibilityObtained" text  NULL ,
    "FinancialResponsibilityBondRatingTest" text  NULL ,
    "FinancialResponsibilityCommercialInsurance" text  NULL ,
    "FinancialResponsibilityGuarantee" text  NULL ,
    "FinancialResponsibilityLetterOfCredit" text  NULL ,
    "FinancialResponsibilityLocalGovernmentFinancialTest" text  NULL ,
    "FinancialResponsibilityRiskRetentionGroup" text  NULL ,
    "FinancialResponsibilitySelfInsuranceFinancialTest" text  NULL ,
    "FinancialResponsibilityStateFund" text  NULL ,
    "FinancialResponsibilitySuretyBond" text  NULL ,
    "FinancialResponsibilityTrustFund" text  NULL ,
    "FinancialResponsibilityOtherMethod" text  NULL ,
    "USTReportedRelease" text  NULL ,
    "AssociatedUSTReleaseID" text  NULL );