create or replace view "trustd_release"."v_lust" as
 SELECT DISTINCT ("TrUSTD_LUST_template_20220714"."FacilityID")::character varying AS "FacilityID",
    ("TrUSTD_LUST_template_20220714"."TankIDAssociatedwithRelease")::character varying AS "TankIDAssociatedwithRelease",
    ("TrUSTD_LUST_template_20220714"."LUSTID")::character varying AS "LUSTID",
    ("TrUSTD_LUST_template_20220714"."FederallyReportableRelease")::character varying AS "FederallyReportableRelease",
    ("TrUSTD_LUST_template_20220714"."SiteName")::character varying AS "SiteName",
    ("left"("TrUSTD_LUST_template_20220714"."SiteAddress", 100))::character varying AS "SiteAddress",
    ("TrUSTD_LUST_template_20220714"."SiteAddress2")::character varying AS "SiteAddress2",
    ("TrUSTD_LUST_template_20220714"."SiteCity")::character varying AS "SiteCity",
    ("TrUSTD_LUST_template_20220714"."Zipcode")::character varying AS "Zipcode",
    ("TrUSTD_LUST_template_20220714"."County")::character varying AS "County",
    ("TrUSTD_LUST_template_20220714"."State")::character varying AS "State",
    ("TrUSTD_LUST_template_20220714"."EPARegion")::integer AS "EPARegion",
    NULL::character varying AS "FacilityType",
    ("TrUSTD_LUST_template_20220714"."TribalSite")::character varying AS "TribalSite",
    NULL::character varying AS "Tribe",
    "TrUSTD_LUST_template_20220714"."Latitude",
    "TrUSTD_LUST_template_20220714"."Longitude",
    ("TrUSTD_LUST_template_20220714"."CoordinateSource")::character varying AS "CoordinateSource",
    ("TrUSTD_LUST_template_20220714"."LUSTStatus")::character varying AS "LUSTStatus",
    ("TrUSTD_LUST_template_20220714"."ReportedDate")::date AS "ReportedDate",
    ("TrUSTD_LUST_template_20220714"."NFADate")::date AS "NFADate",
    ("TrUSTD_LUST_template_20220714"."MediaImpactedSoil")::character varying AS "MediaImpactedSoil",
    ("TrUSTD_LUST_template_20220714"."MediaImpactedGroundwater")::character varying AS "MediaImpactedGroundwater",
    ("TrUSTD_LUST_template_20220714"."MediaImpactedSurfaceWater")::character varying AS "MediaImpactedSurfaceWater",
    ("TrUSTD_LUST_template_20220714"."SubstanceReleased1")::character varying AS "SubstanceReleased1",
    ("TrUSTD_LUST_template_20220714"."QuantityReleased1")::character varying AS "QuantityReleased1",
    ("TrUSTD_LUST_template_20220714"."Unit1")::character varying AS "Unit1",
    ("TrUSTD_LUST_template_20220714"."SubstanceReleased2")::character varying AS "SubstanceReleased2",
    ("TrUSTD_LUST_template_20220714"."QuantityReleased2")::character varying AS "QuantityReleased2",
    ("TrUSTD_LUST_template_20220714"."Unit2")::character varying AS "Unit2",
    ("TrUSTD_LUST_template_20220714"."SubstanceReleased3")::character varying AS "SubstanceReleased3",
    NULL::character varying AS "QuantityReleased3",
    ("TrUSTD_LUST_template_20220714"."Unit3")::character varying AS "Unit3",
    ("TrUSTD_LUST_template_20220714"."SubstanceReleased4")::character varying AS "SubstanceReleased4",
    NULL::character varying AS "QuantityReleased4",
    ("TrUSTD_LUST_template_20220714"."Unit4")::character varying AS "Unit4",
    ("TrUSTD_LUST_template_20220714"."SubstanceReleased5")::character varying AS "SubstanceReleased5",
    NULL::character varying AS "QuantityReleased5",
    ("TrUSTD_LUST_template_20220714"."Unit5")::character varying AS "Unit5",
    ("TrUSTD_LUST_template_20220714"."SourceOfRelease1")::character varying AS "SourceOfRelease1",
    ("TrUSTD_LUST_template_20220714"."CauseOfRelease1")::character varying AS "CauseOfRelease1",
    ("TrUSTD_LUST_template_20220714"."SourceOfRelease2")::character varying AS "SourceOfRelease2",
    ("TrUSTD_LUST_template_20220714"."CauseOfRelease2")::character varying AS "CauseOfRelease2",
    ("TrUSTD_LUST_template_20220714"."SourceOfRelease3")::character varying AS "SourceOfRelease3",
    ("TrUSTD_LUST_template_20220714"."CauseOfRelease3")::character varying AS "CauseOfRelease3",
    ("TrUSTD_LUST_template_20220714"."HowReleaseDetected")::character varying AS "HowReleaseDetected",
    NULL::character varying AS "CorrectiveActionStrategy1",
    NULL::date AS "CorrectiveActionStrategy1StartDate",
    NULL::character varying AS "CorrectiveActionStrategy2",
    NULL::date AS "CorrectiveActionStrategy2StartDate",
    NULL::character varying AS "CorrectiveActionStrategy3",
    NULL::date AS "CorrectiveActionStrategy3StartDate",
    ("TrUSTD_LUST_template_20220714"."ClosedWithContamination")::character varying AS "ClosedWithContamination",
    ("TrUSTD_LUST_template_20220714"."NoFurtherActionLetterURL")::character varying AS "NoFurtherActionLetterURL",
    ("TrUSTD_LUST_template_20220714"."MilitaryDoDSite")::character varying AS "MilitaryDoDSite",
    NULL::double precision AS gc_latitude,
    NULL::double precision AS gc_longitude,
    NULL::character varying AS gc_coordinate_source,
    NULL::character varying AS gc_address_type
   FROM trustd_release."TrUSTD_LUST_template_20220714";