select * from tblGeoSite_LatLong;

CREATE TABLE `tblGeoSite_LatLong` (
	FACILITYID VARCHAR(9),
	NAME VARCHAR(60),
	ADDRESS VARCHAR(50),
	ADDRESS2 VARCHAR(40),
	CITY VARCHAR(40),
	ZIP VARCHAR(5),
	ZIPEXTENSION VARCHAR(4),
	REGION VARCHAR(2),
	COUNTY SMALLINT,
	HCOLLCODE VARCHAR(2),
	HACCURACY NUMERIC(6,2),
	PDOP NUMERIC(4,2),
	SCORE SMALLINT,
	SOURCESCAL INTEGER,
	GEOOWNER VARCHAR(2),
	HACCURUOM VARCHAR(6),
	GEOTYPNAME VARCHAR(6),
	HDATUMNAME VARCHAR(5),
	REFPTCODE VARCHAR(2),
	SOURCECODE VARCHAR(2),
	GEOCOLLECTEDBY VARCHAR(50),
	EASTING DOUBLE,
	NORTHING DOUBLE,
	UTM_ZONE VARCHAR(50),
	VERIFIED DOUBLE,
	`PRIMARY` DOUBLE,
	`SENSITIVE` DOUBLE,
	GPSMAKEMODEL VARCHAR(35),
	EPEORFOM VARCHAR(3),
	EPE_FOMMSRMNT NUMERIC(6,2),
	DATECOLLECTED TIMESTAMP,
	DATEADDED TIMESTAMP,
	DATEEDITED TIMESTAMP,
	USERNAME VARCHAR(15),
	GISCOMMENTS VARCHAR(254),
	converted_lat double,
	converted_long double
);
CREATE INDEX TBLGEOSITELATLONG_FACILITYID ON `tblGeoSite_LatLong` (FACILITYID);
CREATE INDEX TBLGEOSITELATLONG_HCOLLCODE ON `tblGeoSite_LatLong` (HCOLLCODE);
CREATE INDEX TBLGEOSITELATLONG_REFPTCODE ON `tblGeoSite_LatLong` (REFPTCODE);
CREATE INDEX TBLGEOSITELATLONG_SOURCECODE ON `tblGeoSite_LatLong` (SOURCECODE);



select * from tblOwner;