CREATE TABLE public.ust_element_mapping_bkup_20241231 (
    "ust_element_mapping_id" integer  NULL ,
    "ust_control_id" integer  NULL ,
    "mapping_date" date  NULL ,
    "epa_table_name" character varying(100)  NULL ,
    "epa_column_name" character varying(100)  NULL ,
    "organization_table_name" character varying(100)  NULL ,
    "organization_column_name" character varying(100)  NULL ,
    "organization_join_table" character varying(100)  NULL ,
    "organization_join_column" character varying(100)  NULL ,
    "programmer_comments" text  NULL ,
    "organization_comments" text  NULL ,
    "deagg_table_name" character varying(100)  NULL ,
    "deagg_column_name" character varying(100)  NULL ,
    "epa_comments" character varying(4000)  NULL ,
    "organization_join_fk" character varying(100)  NULL ,
    "organization_join_column2" character varying(100)  NULL ,
    "organization_join_column3" character varying(100)  NULL ,
    "organization_join_fk2" character varying(100)  NULL ,
    "organization_join_fk3" character varying(100)  NULL ,
    "query_logic" character varying(4000)  NULL );