create or replace view "trustd_ust"."v_ut_tank_system" as
 SELECT b.tank_system_id,
    b.facility_id,
    b.tank_name,
    b.federal_regulated_tank,
    b.tank_capacity,
    b.substance_desc,
    b.date_installed,
    b.date_last_used,
    b.date_closed,
    b.closure_status_desc,
    b.obs_tank_mat_desc,
    b.obs_tank_mods_desc,
    b.obs_pipe_mat_desc,
    b.obs_pipe_repaired,
    b.pipe_type_desc,
    b.obs_ld_other_method,
    b.obs_over_fill_installed,
    b.obs_spill_installed,
    b.cor_prot_method,
    b.cor_prot_comment,
    b.leak_det_or_clean_close,
    b.obs_overfill_protection_type,
    b.obs_atg_manufacturer,
    b.obs_atg_model,
    b.obs_sir_vendor,
    b.tank_status,
    b.date_of_tank_sts_chg,
    b.created_by,
    b.created_date,
    b.updated_by,
    b.updated_date,
    b.ast,
    b.obs_tank_emergen,
    b.obs_substance_comments,
    b.tank_attributes,
    b.obs_overfill_protections,
    b.obs_spill_preventions,
    b.obs_piping_attributes,
    b.obs_piping_deliveries,
    b.obs_substances,
    b.obs_tank_release_detections,
    b.obs_pipe_release_detections,
    b.tank_repaired,
    b.cp_testing_date,
    b.repair_date,
    b.site_assessed,
    b.date_assessed,
    b.date_nfa,
    b.ust_type,
    b.cp_install_date,
    b.drop_tube,
    b.triennial_spill_buckt_dt,
    b.triennial_overfill_date,
    b.annual_operability_date,
    b.annual_annular_sensor_dt,
    b.triennial_stp_sump_date,
    b.annual_stp_sump_senser,
    b.triennial_udc_test_date,
    b.annual_udc_sensor_date,
    b.last_annual_walk_insp_dt,
    b.last_month_walk_insp_dt,
    b.tank_attributes_comments,
    b.ust_type_obs,
    b.cp_repaired,
    b.cp_repair_date
   FROM (( SELECT ut_tank_system.facility_id,
            ut_tank_system.tank_name,
            max(COALESCE(ut_tank_system.date_installed, (CURRENT_DATE)::text)) AS date_installed
           FROM trustd_ust.ut_tank_system
          GROUP BY ut_tank_system.facility_id, ut_tank_system.tank_name) a
     JOIN trustd_ust.ut_tank_system b ON (((a.facility_id = b.facility_id) AND (a.tank_name = b.tank_name) AND (a.date_installed = COALESCE(b.date_installed, (CURRENT_DATE)::text)))));