create view "SC_LUST".v_lust as
select 
	"FacilityID",
	null as "TankIDAssociatedwithRelease",
	"LUSTID",
	null as "FederallyReportableRelease",
	"SiteName",
	"SiteAddress",
	null as "SiteAddress2",
	"SiteCity",
	"ZipCode",
	null as "County",
	"State",
	"EPARegion",
	null as "FacilityType",
	null as "TribalSite",
	null as "Tribe",
	"Latitude",
	"Longitude",
	null as "CoordinateSource",
	"LUSTStatus",
	"ReportedDate",
	"NFADate",
	"MediaImpactedSoil",
	"MediaImpactedGroundwater",
	"MediaImpactedSurfaceWater",
	"SubstanceReleased1",
	null as "QuantityReleased1",
	null as "Unit1",
	null as "SubstanceReleased2",
	null as "QuantityReleased2",
	null as "Unit2",
	null as "SubstanceReleased3",
	null as "QuantityReleased3",
	null as "Unit3",
	null as "SubstanceReleased4",
	null as "QuantityReleased4",
	null as "Unit4",
	null as "SubstanceReleased5",
	null as "QuantityReleased5",
	null as "Unit5",
	null as "SourceOfRelease1",
	null as "CauseOfRelease1",
	null as "SourceOfRelease2",
	null as "CauseOfRelease2",
	null as "SourceOfRelease3",
	null as "CauseOfRelease3",
	null as "HowReleaseDetected",
	null as "RemediationStrategy1",
	null as "RemediationStrategy1StartDate",
	null as "RemediationStrategy2",
	null as "RemediationStrategy2StartDate",
	null as "RemediationStrategy3",
	null as "RemediationStrategy3StartDate",
	"ClosedWithContamination",
	null as "NoFurtherActionLetterURL",
	null as "MilitaryDoDSite"
from "SC_LUST"."SC_LUST_template";

select * from "SC_LUST".v_lust order by "FacilityID";