CREATE TABLE ok_ust.erg_OK_UST_Facility_Data_clean_cui (
    "facility_number" bigint  NULL ,
    "Status" text  NULL ,
    "facility_id" bigint  NULL ,
    "Type" text  NULL ,
    "Name" text  NULL ,
    "Name_cui" character varying(20)  NULL ,
    "Address" text  NULL ,
    "Address2" text  NULL ,
    "City" text  NULL ,
    "State" text  NULL ,
    "Zip" bigint  NULL ,
    "Phone" double precision  NULL ,
    "OwnerID" bigint  NULL ,
    "Trust land" boolean  NULL ,
    "Tribe" text  NULL ,
    "HighFlow Inspection" boolean  NULL ,
    "Pumps" bigint  NULL ,
    "Tanks" bigint  NULL ,
    "Latitude" double precision  NULL ,
    "Longitude" double precision  NULL );