CREATE TABLE ok_ust.erg_trustd_ust_tribe_analysis (
    "Region" bigint  NULL ,
    "Land Location ID" bigint  NULL ,
    "Location ID" text  NULL ,
    "Tribe" text  NULL ,
    "Name" text  NULL ,
    "Address" text  NULL ,
    "City" text  NULL ,
    "County" text  NULL ,
    "State" text  NULL ,
    "Zip" double precision  NULL ,
    "Latitude" double precision  NULL ,
    "Longitude" double precision  NULL ,
    "Lat Lon Source" text  NULL ,
    "Open USTs" bigint  NULL ,
    "Closed USTs" bigint  NULL ,
    "Temporarily Out of Service USTs" bigint  NULL ,
    "Abandoned USTs" bigint  NULL ,
    "Facility Status" text  NULL ,
    "Date of Last Inspection" timestamp without time zone  NULL );