CREATE TABLE ok_ust.erg_state_ust_tribe_analysis (
    "FacilityID" bigint  NULL ,
    "FacilityName" text  NULL ,
    "OwnerType" text  NULL ,
    "FacilityType1" text  NULL ,
    "FacilityType2" double precision  NULL ,
    "FacilityAddress1" text  NULL ,
    "FacilityAddress2" text  NULL ,
    "FacilityCity" text  NULL ,
    "FacilityCounty" double precision  NULL ,
    "FacilityZipCode" bigint  NULL ,
    "FacilityState" text  NULL ,
    "FacilityEPARegion" bigint  NULL ,
    "FacilityTribalSite" text  NULL ,
    "FacilityTribe" text  NULL ,
    "FacilityLatitude" double precision  NULL ,
    "FacilityLongitude" double precision  NULL ,
    "FacilityCoordinateSource" double precision  NULL ,
    "FacilityOwnerCompanyName" text  NULL ,
    "FacilityOperatorCompanyName" double precision  NULL ,
    "FinancialResponsibilityObtained" double precision  NULL ,
    "FinancialResponsibilityBondRatingTest" double precision  NULL ,
    "FinancialResponsibilityCommercialInsurance" double precision  NULL ,
    "FinancialResponsibilityGuarantee" double precision  NULL ,
    "FinancialResponsibilityLetterOfCredit" double precision  NULL ,
    "FinancialResponsibilityLocalGovernmentFinancialTest" double precision  NULL ,
    "FinancialResponsibilityRiskRetentionGroup" double precision  NULL ,
    "FinancialResponsibilitySelfInsuranceFinancialTest" double precision  NULL ,
    "FinancialResponsibilityStateFund" double precision  NULL ,
    "FinancialResponsibilitySuretyBond" double precision  NULL ,
    "FinancialResponsibilityTrustFund" double precision  NULL ,
    "FinancialResponsibilityOtherMethod" double precision  NULL ,
    "USTReportedRelease" double precision  NULL ,
    "AssociatedUSTReleaseID" double precision  NULL ,
    "FacilityComment" double precision  NULL );