CREATE TABLE ut_ust.erg_ut_ust_clean_cui (
    "﻿DERRID" bigint  NULL ,
    "LOCNAME" text  NULL ,
    "LOCNAME_cui" boolean  NULL ,
    "LOCSTR" text  NULL ,
    "LOCCITY" text  NULL ,
    "LOCCOUNTY" text  NULL ,
    "LOCSTATE" text  NULL ,
    "LOCZIP" bigint  NULL ,
    "FACILITYDE" text  NULL ,
    "NORTHING" double precision  NULL ,
    "EASTING" double precision  NULL ,
    "UTMDESC" text  NULL ,
    "HEALTHDIST" bigint  NULL ,
    "OWNERNAME" text  NULL ,
    "OWNERADDRESS" text  NULL ,
    "OWNERCITY" text  NULL ,
    "OWNERCOUNTY" text  NULL ,
    "OWNERSTATE" text  NULL ,
    "OWNERZIP" bigint  NULL ,
    "MAPLABEL" text  NULL ,
    "RELEASE" bigint  NULL ,
    "TANK" bigint  NULL ,
    "OPENRELEASE" bigint  NULL ,
    "SITEDESC" text  NULL ,
    "OPENREGAST" bigint  NULL ,
    "REGAST" bigint  NULL ,
    "OPENTANK" bigint  NULL ,
    "FACTSHEET" bigint  NULL ,
    "HYPERLINK" text  NULL ,
    "facility_id" bigint  NULL ,
    "FORKLIFT_HASH" text  NULL ,
    "DDLat" double precision  NULL ,
    "DDLon" double precision  NULL ,
    "ORIG_OID" bigint  NULL );