create view "SC_UST".v_ust as
select 
	"FacilityID",
	"FacilityName",
	null as "OwnerType",
	null as "FacilityType1",
	null as "FacilityType2",
	"FacilityAddress1",
	null as "FacilityAddress2",
	"FacilityCity",
	null as "FacilityCounty",
	null as "FacilityZipCode",
	"FacilityPhoneNumber",
	"FacilityState",
	"FacilityEPARegion",
	null as "FacilityTribalSite",
	null as "FacilityTribe",
	"FacilityLatitude",
	"FacilityLongitude",
	null as "FacilityCoordinateSource",
	"FacilityOwnerName" as "FacilityOwnerCompanyName",
	null as "FacilityOwnerLastName",
	null as "FacilityOwnerFirstName",
	"FacilityOwnerAddress1",
	null as "FacilityOwnerAddress2",
	"FacilityOwnerCity",
	null as "FacilityOwnerCounty",
	"FacilityOwnerZipCode",
	"FacilityOwnerState",
	null as "FacilityOwnerPhoneNumber",
	null as "FacilityOwnerEmail",
	null as "FacilityOperatorName",
	null as "FacilityOperatorLastName",
	null as "FacilityOperatorFirstName",
	null as "FacilityOperatorAddress1",
	null as "FacilityOperatorAddress2",
	null as "FacilityOperatorCity",
	null as "FacilityOperatorCounty",
	null as "FacilityOperatorZipCode",
	null as "FacilityOperatorState",
	null as "FacilityOperatorPhoneNumber",
	null as "FacilityOperatorEmail",
	"FinancialResponsibilityBondRatingTest",
	"FinancialResponsibilityCommercialInsurance",
	"FinancialResponsibilityGuarantee",
	"FinancialResponsibilityLetterOfCredit",
	null as "FinancialResponsibilityLocalGovernmentFinancialTest",
	null as "FinancialResponsibilityRiskRetentionGroup",
	"FinancialResponsibilitySelfInsuranceFinancialTest",
	null as "FinancialResponsibilityStateFund",
	"FinancialResponsibilitySuretyBond",
	"FinancialResponsibilityTrustFund",
	"FinancialResponsibilityOtherMethod",
	null as "FinancialResponsibilityNotRequired",
	case when "FinancialResponsibilityBondRatingTest" is not null or
			  "FinancialResponsibilityCommercialInsurance" is not null or
			  "FinancialResponsibilityGuarantee" is not null or
			  "FinancialResponsibilityLetterOfCredit" is not null or
			  "FinancialResponsibilitySelfInsuranceFinancialTest" is not null or
			  "FinancialResponsibilitySuretyBond" is not null or
			  "FinancialResponsibilityTrustFund" is not null or
			  "FinancialResponsibilityOtherMethod" is not null then 'Yes' end as "FinancialResponsibilityObtained",
	null as "Compliance",
	"TankID",
	null as "TankLocation",
	null as "FederallyRegulated",
	"TankStatus",
	null as "FieldConstructed",
	null as "EmergencyGenerator",
	null as "AirportHydrantSystem",
	null as "MultipleTanks",
	null as "ClosureDate",
	null as "InstallationDate",
	"CompartmentalizedUST",
	null as "NumberofCompartments",
	"TankSubstanceStored",
	"CompartmentID",
	"CompartmentSubstanceStored",
	"TankCapacityGallons",
	"CompartmentCapacityGallons",
	null as "LinedTank",
	null as "ExcavationLiner",
	null as "TankWallType",
	null as "MaterialDescription",
	null as "TankRepaired",
	null as "TankRepairDate",
	null as "CertofInstallation",
	null as "PipingMaterialDescription",
	null as "PipingFlexConnector",
	null as "PipingStyle",
	null as "PipingWallType",
	null as "PipingUDCForEveryDispenser",
	null as "PipingRepaired",
	null as "PipingRepairDate",
	null as "TankCorrosionProtectionSacrificialAnode",
	null as "TankCorrosionProtectionAnodesInstalledOrRetrofitted",
	null as "TankCorrosionProtectionImpressedCurrent",
	null as "TankCorrosionProtectionImpressedCurrentInstalledOrRetrofitted",
	null as "TankCorrosionProtectionCathodicNotRequired",
	null as "TankCorrosionProtectionInteriorLining",
	null as "TankCorrosionProtectionOther",
	null as "TankCorrosionProtectionUnknown",
	null as "TankCorrosionProtectionLinedPostinstallation",
	null as "PipingCorrosionProtectionSacrificialAnodes",
	null as "PipingCorrosionProtectionAnodesInstalledOrRetrofitted",
	null as "PipingCorrosionProtectionImpressedCurrent",
	null as "PipingCorrosionProtectionImpressedCurrentInstalledOrRetrofitted",
	null as "PipingCorrosionProtectionCathodicNotRequired",
	null as "PipingCorrosionProtectionExternalCoating",
	null as "PipingCorrosionProtectionOther",
	null as "PipingCorrosionProtectionUnknown",
	"BallFloatValve",
	"AutomaticShutoffDevice" as "FlowShutoffDevice",
	"OverfillAlarm" as "HighLevelAlarm",
	null as "OverfillProtectionPrimary",
	null as "OverfillProtectionSecondary",
	null as "PrimaryOverfillInstallDate",
	null as "SecondaryOverfillInstallDate",
	null as "SpillBucketInstalled",
	null as "SpillBucketWallType",
	null as "DrainPresent",
	null as "PumpPresent",
	null as "InterstitialMonitoringContinualElectric",
	null as "InterstitialMonitoringManual",
	null as "AutomaticTankGauging",
	null as "AutomaticTankGaugingReleaseDetection",
	null as "AutomaticTankGaugingContinuousLeakDetection",
	null as "ManualTankGauging",
	null as "StatisticalInventoryReconciliation",
	null as "TankTightnessTesting",
	null as "GroundwaterMonitoring",
	null as "SubpartK",
	null as "VaporMonitoring",
	null as "ElectronicLineLeak",
	null as "MechanicalLineLeak",
	null as "AutomatedIntersticialMonitoring",
	null as "SafeSuction",
	null as "AmericanSuction",
	null as "PipingSubpartK",
	null as "HighPressure",
	null as "PrimaryReleaseDetectionType",
	null as "SecondReleaseDetectionType",
	null as "PipeSecondaryContainment",
	null as "PipeInstallDate",
	"USTReportedRelease",
	"AssociatedLUSTID",
	null as "LastInspectionDate"
from "SC_UST"."SC_UST_template";

select * from "SC_UST"."SC_UST_template" order by "FacilityID","TankID";


