CREATE TABLE wv_release.erg_release (
    "release_control_id" integer  NULL ,
    "FacilityID" character varying(50)  NULL ,
    "TankIDAssociatedwithRelease" character varying(50)  NULL ,
    "ReleaseID" character varying(50)  NULL ,
    "FederallyReportableRelease" character varying(7)  NULL ,
    "SiteName" character varying(200)  NULL ,
    "SiteAddress" character varying(100)  NULL ,
    "SiteAddress2" character varying(100)  NULL ,
    "SiteCity" character varying(100)  NULL ,
    "Zipcode" character varying(10)  NULL ,
    "County" character varying(100)  NULL ,
    "State" character varying(2)  NULL ,
    "EPARegion" integer  NULL ,
    "FacilityType" character varying(100)  NULL ,
    "TribalSite" character varying(7)  NULL ,
    "Tribe" character varying(50)  NULL ,
    "Latitude" double precision  NULL ,
    "Longitude" double precision  NULL ,
    "CoordinateSource" character varying(100)  NULL ,
    "USTReleaseStatus" character varying(200)  NULL ,
    "ReportedDate" date  NULL ,
    "NFADate" date  NULL ,
    "MediaImpactedSoil" character varying(3)  NULL ,
    "MediaImpactedGroundwater" character varying(3)  NULL ,
    "MediaImpactedSurfaceWater" character varying(3)  NULL ,
    "ReleaseDiscovered" character varying(100)  NULL ,
    "ClosedWithContamination" character varying(7)  NULL ,
    "NoFurtherActionLetterURL" character varying(2000)  NULL ,
    "MilitaryDoDSite" character varying(7)  NULL ,
    "ReleaseComment" character varying(4000)  NULL );