CREATE TABLE wv_release.erg_wv_release_clean_cui (
    "release_control_id" bigint  NULL ,
    "FacilityID" bigint  NULL ,
    "TankIDAssociatedwithRelease" double precision  NULL ,
    "ReleaseID" text  NULL ,
    "FederallyReportableRelease" double precision  NULL ,
    "SiteName" text  NULL ,
    "SiteName_cui" boolean  NULL ,
    "SiteAddress" text  NULL ,
    "SiteAddress2" double precision  NULL ,
    "SiteCity" text  NULL ,
    "Zipcode" text  NULL ,
    "County" text  NULL ,
    "State" text  NULL ,
    "EPARegion" bigint  NULL ,
    "FacilityType" double precision  NULL ,
    "TribalSite" double precision  NULL ,
    "Tribe" double precision  NULL ,
    "Latitude" double precision  NULL ,
    "Longitude" double precision  NULL ,
    "CoordinateSource" double precision  NULL ,
    "USTReleaseStatus" text  NULL ,
    "ReportedDate" timestamp without time zone  NULL ,
    "NFADate" timestamp without time zone  NULL ,
    "MediaImpactedSoil" text  NULL ,
    "MediaImpactedGroundwater" text  NULL ,
    "MediaImpactedSurfaceWater" double precision  NULL ,
    "ReleaseDiscovered" double precision  NULL ,
    "ClosedWithContamination" double precision  NULL ,
    "NoFurtherActionLetterURL" double precision  NULL ,
    "MilitaryDoDSite" double precision  NULL ,
    "ReleaseComment" double precision  NULL );