create or replace view "or_release"."v_lust" as
 SELECT DISTINCT ("OR_LUST_template_20230113"."FacilityID")::character varying AS "FacilityID",
    ("OR_LUST_template_20230113"."TankIDAssociatedwithRelease")::character varying AS "TankIDAssociatedwithRelease",
    ("OR_LUST_template_20230113"."LUSTID")::character varying AS "LUSTID",
    ("OR_LUST_template_20230113"."FederallyReportableRelease")::character varying AS "FederallyReportableRelease",
    ("OR_LUST_template_20230113"."SiteName")::character varying AS "SiteName",
    ("OR_LUST_template_20230113"."SiteAddress")::character varying AS "SiteAddress",
    ("OR_LUST_template_20230113"."SiteAddress2")::character varying AS "SiteAddress2",
    ("OR_LUST_template_20230113"."SiteCity")::character varying AS "SiteCity",
    ("OR_LUST_template_20230113"."Zipcode")::character varying AS "Zipcode",
    ("OR_LUST_template_20230113"."County")::character varying AS "County",
    ("OR_LUST_template_20230113"."State")::character varying AS "State",
    ("OR_LUST_template_20230113"."EPARegion")::integer AS "EPARegion",
    ("OR_LUST_template_20230113"."FacilityType")::character varying AS "FacilityType",
    ("OR_LUST_template_20230113"."TribalSite")::character varying AS "TribalSite",
    ("OR_LUST_template_20230113"."Tribe")::character varying AS "Tribe",
    "OR_LUST_template_20230113"."Latitude",
    "OR_LUST_template_20230113"."Longitude",
    ("OR_LUST_template_20230113"."CoordinateSource")::character varying AS "CoordinateSource",
    ("OR_LUST_template_20230113"."LUSTStatus")::character varying AS "LUSTStatus",
    ("OR_LUST_template_20230113"."ReportedDate")::date AS "ReportedDate",
    ("OR_LUST_template_20230113"."NFADate")::date AS "NFADate",
    ("OR_LUST_template_20230113"."MediaImpactedSoil")::character varying AS "MediaImpactedSoil",
    ("OR_LUST_template_20230113"."MediaImpactedGroundwater")::character varying AS "MediaImpactedGroundwater",
    ("OR_LUST_template_20230113"."MediaImpactedSurfaceWater")::character varying AS "MediaImpactedSurfaceWater",
    ("OR_LUST_template_20230113"."SubstanceReleased1")::character varying AS "SubstanceReleased1",
    ("OR_LUST_template_20230113"."QuantityReleased1")::character varying AS "QuantityReleased1",
    NULL::character varying AS "Unit1",
    ("OR_LUST_template_20230113"."SubstanceReleased2")::character varying AS "SubstanceReleased2",
    ("OR_LUST_template_20230113"."QuantityReleased2")::character varying AS "QuantityReleased2",
    NULL::character varying AS "Unit2",
    ("OR_LUST_template_20230113"."SubstanceReleased3")::character varying AS "SubstanceReleased3",
    ("OR_LUST_template_20230113"."QuantityReleased3")::character varying AS "QuantityReleased3",
    NULL::character varying AS "Unit3",
    ("OR_LUST_template_20230113"."SubstanceReleased4")::character varying AS "SubstanceReleased4",
    NULL::character varying AS "QuantityReleased4",
    NULL::character varying AS "Unit4",
    ("OR_LUST_template_20230113"."SubstanceReleased5")::character varying AS "SubstanceReleased5",
    NULL::character varying AS "QuantityReleased5",
    NULL::character varying AS "Unit5",
    ("OR_LUST_template_20230113"."SourceOfRelease1")::character varying AS "SourceOfRelease1",
    ("OR_LUST_template_20230113"."CauseOfRelease1")::character varying AS "CauseOfRelease1",
    NULL::character varying AS "SourceOfRelease2",
    NULL::character varying AS "CauseOfRelease2",
    NULL::character varying AS "SourceOfRelease3",
    NULL::character varying AS "CauseOfRelease3",
    ("OR_LUST_template_20230113"."HowReleaseDetected")::character varying AS "HowReleaseDetected",
    ("OR_LUST_template_20230113"."RemediationStrategy1")::character varying AS "CorrectiveActionStrategy1",
    NULL::date AS "CorrectiveActionStrategy1StartDate",
    ("OR_LUST_template_20230113"."RemediationStrategy2")::character varying AS "CorrectiveActionStrategy2",
    NULL::date AS "CorrectiveActionStrategy2StartDate",
    ("OR_LUST_template_20230113"."RemediationStrategy3")::character varying AS "CorrectiveActionStrategy3",
    NULL::date AS "CorrectiveActionStrategy3StartDate",
    ("OR_LUST_template_20230113"."ClosedWithContamination")::character varying AS "ClosedWithContamination",
    ("OR_LUST_template_20230113"."NoFurtherActionLetterURL")::character varying AS "NoFurtherActionLetterURL",
    ("OR_LUST_template_20230113"."MilitaryDoDSite")::character varying AS "MilitaryDoDSite",
    NULL::double precision AS gc_latitude,
    NULL::double precision AS gc_longitude,
    NULL::character varying AS gc_coordinate_source,
    NULL::character varying AS gc_address_type
   FROM or_release."OR_LUST_template_20230113";