

------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Update the control table 

--EITHER:
--use insert_control.py to insert into public.ust_control
--OR:


--the script above returned a new ust_control_id of 11 for this dataset:
select * from public.ust_control where ust_control_id = 23;



------------------------------------------------------------------------------------------------------------------------------------------------------------------------





------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--Upload the state data 
/* 
EITHER:
script import_data_file_files.py will create the correct schema (if it doesn't yet exist), 
then upload all .xlsx, .xls, .csv, and .txt in the specified directory to this schema. 
To run, set these variables:

organization_id = 'OK' 
# Enter a directory (not a path to a specific file) for ust_path and ust_path
# Set to None if not applicable
ust_path = 'C:\Users\JChilton\repo\UST\ust\sql\states\SD\UST' 
overwrite_table = False 


load the rease data too to populate a field fields in UST from it
release_path = r'C:\Users\JChilton\OneDrive - Eastern Research Group\Desktop\UST\MD\Release\CASES 04-03-24\CASES 04-03-24'

OR:
manually in the database, create schema ok_ust if it does not exist, then manually upload the state data
*/

------------------------------------------------------------------------------------------------------------------------------------------------------------------------

alter table "OK_UST_Facility_Data"  rename column "FacilityID" to facility_id;

alter table "OK_UST_Data"  rename column "Tank #" to tank_name;



------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
Generate SQL statements to do the inserts into ust_element_mapping. 
Run the query below, paste the results into your console, then do a global replace of 9 for the ust_control_id 
Next, go through each generated SQL statement and do the following:
If there is no matching column in the state's data, delete the SQL statement 
If there is a matching column in the state's data, update the tanks and ORG_COL_NAME variables to match the state's data 
If you have questions or comments, replace the "null" with your comment. 
After you have updated all the SQL statements, run them to update the database. 
*/
select * from public.v_ust_element_summary_sql;

/*you can run this SQL so you can copy and paste table and column names into the SQL statements generated by the query above
select table_name, column_name from information_schema.columns 
where table_schema = 'ok_ust' order by table_name, ordinal_position;
*/




insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_facility','facility_id','OK_UST_Facility_Data','facility_id',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_facility','facility_name','OK_UST_Facility_Data','Name',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_facility','owner_type_id','OK_UST_Owner_Data','Type',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_facility','facility_type1','OK_UST_Facility_Data','Type',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_facility','facility_address1','OK_UST_Facility_Data','Address',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_facility','facility_address2','OK_UST_Facility_Data','Address2',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_facility','facility_city','OK_UST_Facility_Data','City',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_facility','facility_zip_code','OK_UST_Facility_Data','Zip',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_facility','facility_tribal_site','OK_UST_Facility_Data','Trust land',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_facility','facility_tribe','OK_UST_Facility_Data','Tribe',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_facility','facility_latitude','OK_UST_Facility_Data','Latitude',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_facility','facility_longitude','OK_UST_Facility_Data','Longitude',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_facility','facility_owner_company_name','OK_UST_Owner_Data','Name',null);


insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_tank','facility_id','OK_UST_Data','FacilityID',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_tank','multiple_tanks','OK_UST_Data','Manifold',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_tank','tank_name','OK_UST_Data','tank_name',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_tank','tank_status_id','OK_UST_Data','Status',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_tank','tank_closure_date','OK_UST_Data','ClosedDate',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_tank','tank_installation_date','OK_UST_Data','InstalledDate',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_tank','compartmentalized_ust','OK_UST_Data','Compartments','where Compartments > 1');
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_tank','number_of_compartments','OK_UST_Data','Compartments',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_tank','tank_material_description_id','OK_UST_Data','Tank Material',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_tank','tank_secondary_containment_id','OK_UST_Data','Tank Construction',null);

insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (ZZ,'ust_compartment','compartment_name','ORG_TAB_NAME','ORG_COL_NAME',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_compartment','facility_id','OK_UST_Data','FacilityID',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_compartment','compartment_name','OK_UST_Data','tank_name',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_compartment','compartment_name','OK_UST_Data','tank_name',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_compartment','compartment_status_id','OK_UST_Data','Status',null);
insert into ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) values (23,'ust_compartment','compartment_capacity_gallons','OK_UST_Data','Capacity',null);

delete from ust_element_mapping where ust_control_id = 23 and epa_column_name = 'tank_name' and epa_table_name = 'ust_compartment'



------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--see what columns in which table we need to map
/*
see what mapping hasn't yet been done for this dataset 
we'll be going through each of the results of this query below
so for each value of epa_column_name from this query result, there will be a 
section below where we generate SQL to perform the mapping 
*/
select epa_table_name, epa_column_name 
from 
	(select distinct epa_table_name, epa_column_name, table_sort_order, column_sort_order
	from v_ust_needed_mapping 
	where ust_control_id = 23 and mapping_complete = 'N'
	order by table_sort_order, column_sort_order) x;
/*
 



*/
------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--owner_type_id
select insert_sql 
from v_ust_needed_mapping_insert_sql 
where ust_control_id = 23 and epa_column_name = 'owner_type_id';

--paste the insert_sql from the first row below, then run the query:
select distinct 
	'insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (' || 1328 || ', ''' || "Type" || ''', '''', null);'
from ok_ust."OK_UST_Owner_Data" order by 1;

select * from public.owner_types;



insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1328, 'Commercial', 'Commercial', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1328, 'County', 'Local Government', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1328, 'Federal', 'Federal Government - Non Military', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1328, 'Indian', 'Tribal Government', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1328, 'Municipal', 'Local Government', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1328, 'Not Listed', 'Other', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1328, 'Private', 'Private', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1328, 'State', 'State Government - Non Military', null);


--facility_type1
select insert_sql 
from v_ust_needed_mapping_insert_sql 
where ust_control_id = 23 and epa_column_name = 'facility_type1';

--paste the insert_sql from the first row below, then run the query:
select distinct 
	'insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (' || 1329 || ', ''' || "Type" || ''', '''', null);'
from ok_ust."OK_UST_Facility_Data" order by 1;

select * from public.facility_types ft ;


insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1329, 'Air Taxi (Airline)', 'Aviation/airport (non-rental car)', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1329, 'Auto Dealership', 'Auto dealership/auto maintenance & repair', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1329, 'Contractor', 'Contractor', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1329, 'Farm', 'Agricultural/farm', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1329, 'Federal Military', 'Military', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1329, 'Federal Non-Military', 'Federal government, non-military', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1329, 'Gas Station', 'Retail fuel sales (non-marina)', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1329, 'Industrial', 'Industrial', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1329, 'Marina', 'Marina', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1329, 'Not Listed', 'Unknown', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1329, 'Petroleum Distributor', 'Bulk plant storage/petroleum distributor', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1329, 'Railroad', 'Railroad', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1329, 'Residential', 'Residential', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1329, 'School', 'School', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1329, 'Truck/Transporter', 'Trucking/transport/fleet operation', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1329, 'Utilities', 'Utility', null);

--tank_status_id
select insert_sql 
from v_ust_needed_mapping_insert_sql 
where ust_control_id = 23 and epa_column_name = 'tank_status_id';

--paste the insert_sql from the first row below, then run the query:
select distinct 
	'insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (' || 1342 || ', ''' || "Status" || ''', '''', null);'
from ok_ust."OK_UST_Data" order by 1;

select * from public.tank_statuses ;

insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1342, 'CIU', 'Currently in use', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1342, 'POU', 'Closed (general)','Please confirm, I assume POU means permanently out of use');
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1342, 'TOU', 'Temporarily out of service', 'Please confirm, I assume TOU means temp out of use');
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1342, 'Xfer', 'Other', 'Please confirm, I assume Xfer means transfer');

--compartment_status_id
select insert_sql 
from v_ust_needed_mapping_insert_sql 
where ust_control_id = 23 and epa_column_name = 'compartment_status_id';

--paste the insert_sql from the first row below, then run the query:
select distinct 
	'insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (' || 1352 || ', ''' || "Status" || ''', '''', null);'
from ok_ust."OK_UST_Data" order by 1;

insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1352, 'CIU', 'Currently in use', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1352, 'POU', 'Closed (general)','Please confirm, I assume POU means permanently out of use');
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1352, 'TOU', 'Temporarily out of service', 'Please confirm, I assume TOU means temp out of use');
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1352, 'Xfer', 'Other', 'Please confirm, I assume Xfer means transfer');


--tank_material_description_id

select insert_sql 
from v_ust_needed_mapping_insert_sql 
where ust_control_id = 23 and epa_column_name = 'tank_material_description_id';

--paste the insert_sql from the first row below, then run the query:
select distinct 
	'insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (' || 1347 || ', ''' || "Tank Material" || ''', '''', null);'
from ok_ust."OK_UST_Data" order by 1;


insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1347, 'Concrete', 'Concrete', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1347, 'Fiberglass Reinforced Plastic', 'Fiberglass reinforced plastic', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1347, 'Steel', 'Steel (NEC)', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1347, 'Steel With Fiberglass', 'Composite/clad (steel w/fiberglass reinforced plastic)', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1347, 'Unknown', 'Unknown', null);

select * from public.tank_material_descriptions tmd 

--tank_secondary_containment_id
select insert_sql 
from v_ust_needed_mapping_insert_sql 
where ust_control_id = 23 and epa_column_name = 'tank_secondary_containment_id';

--paste the insert_sql from the first row below, then run the query:
select distinct 
	'insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (' || 1348 || ', ''' || "Tank Construction" || ''', '''', null);'
from ok_ust."OK_UST_Data" order by 1;

select * from public.tank_secondary_containments tsc 


insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1348, 'Double Walled', 'Double wall', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1348, 'Secondarily Contained / Jacketed', 'Jacketed', null);
insert into ust_element_value_mapping (ust_element_mapping_id, organization_value, epa_value, programmer_comments) values (1348, 'Single Walled', 'Single wall', null);

------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--check if there is any more mapping to do
select distinct epa_table_name, epa_column_name
from v_ust_needed_mapping 
where ust_control_id = 23 and mapping_complete = 'N'
order by 1, 2;

--check if any of the mapping is bad:
select database_lookup_table, epa_value 
from v_ust_bad_mapping 
where ust_control_id = 23 order by 1, 2;

------------------------------------------------------------------------------------------------------------------------------------------------------------------------

/*Step 1: create crosswalk views for columns that use a lookup table
run script org_mapping_xwalks.py to create crosswalk views for all lookup tables 
see new views:*/
select table_name 
from information_schema.tables 
where table_schema = 'ok_ust' and table_type = 'VIEW'
and table_name like '%_xwalk' order by 1;
/*
v_coordinate_source_xwalk
v_piping_style_xwalk
v_piping_wall_type_xwalk
v_state_xwalk
v_substance_xwalk
v_tank_material_description_xwalk
v_tank_status_xwalk
*/

--Step 2: see the EPA tables we need to populate, and in what order
select distinct epa_table_name, table_sort_order
from v_ust_table_population 
where ust_control_id = 23
order by table_sort_order;
/*
ust_facility
ust_tank
ust_tank_substance
ust_compartment
*/

/*Step 3: check if there where any dataset-level comments you need to incorporate:
in this case we need to ignore the aboveground storage tanks,
so add this to the where clause of the ust_release view */
select comments from ust_control where ust_control_id = 23;
--Filter by  ut_facility."TANK" = 1 AND ut_facility."OPENREGAST" = 0 AND ut_facility."REGAST" = 0. 

/*Step 4: work through the tables in order, using the information you collected 
to write views that can be used to populate the data tables 
NOTE! The view queried below (v_ust_table_population_sql) contains columns that help
      construct the select sql for the insertion views, but will require manual 
      oversight and manipulation by you! 
      In particular, check out the organization_join_table and organization_join_column 
      are used!!*/
select organization_table_name_qtd, organization_column_name_qtd,
	selected_column, data_type, character_maximum_length,
	programmer_comments, database_lookup_table, database_lookup_column,
	organization_join_table_qtd, organization_join_column_qtd,
	deagg_table_name, deagg_column_name 
from v_ust_table_population_sql
where ust_control_id = 23 and epa_table_name = 'ust_facility'
order by column_sort_order;

/*Step 5: use the information from the queries above to create the view:
!!! NOTE look at the programmer_comments column to adjust the view if necessary
!!! NOTE also sometimes you need to explicitly cast data types so they match the EPA data tables
!!! NOTE also you may get errors related to data conversion when trying to compile the view
    you are creating here. This is good because it alerts you the data you are trying to
    insert is not compatible with the EPA format. Fix these errors before proceeding! 
!!! NOTE: Remember to do "select distinct" if necessary
!!! NOTE: Some states do not include State or EPA Region in their database, but it is generally
    safe for you to insert these yourself, so add them! (facility_state is a required field! */
drop view ok_ust.v_ust_facility;

create or replace view ok_ust.v_ust_facility as 
select distinct 
"facility_id"::character varying(50) as facility_id,
x."Name"::character varying(100) as facility_name,
owner_type_id as owner_type_id,
facility_type_id as facility_type1,
x."Address"::character varying(100) as facility_address1,
x."Address2"::character varying(100) as facility_address2,
x."City"::character varying(100) as facility_city,
x."Zip"::character varying(10) as facility_zip_code,
case when x."Trust land" is true then 'Yes' else 'No' end as facility_tribal_site,
x."Tribe"::character varying(200) as facility_tribe,
x."Latitude"::double precision as facility_latitude,
x."Longitude"::double precision as facility_longitude,
y."Name"::character varying(100) as facility_owner_company_name,
'OK' as facility_state,
6 as facility_epa_region
from ok_ust."OK_UST_Facility_Data" x 
left join ok_ust."OK_UST_Owner_Data" y on x."OwnerID" = y."Owner ID"
left join ok_ust.v_facility_type_xwalk a on a."organization_value" =x."Type"
left join ok_ust.v_owner_type_xwalk votx on votx."organization_value" =y."Type"
;





--review: 
select * from ok_ust.v_ust_facility;
select count(*) from ok_ust.v_ust_facility;
--13967
--------------------------------------------------------------------------------------------------------------------------
--now repeat for each data table:

--ust_tank 
select organization_table_name_qtd, organization_column_name_qtd,
	selected_column, data_type, character_maximum_length,
	programmer_comments, database_lookup_table, database_lookup_column,
	--organization_join_table_qtd, organization_join_column_qtd,
	deagg_table_name, deagg_column_name 
from v_ust_table_population_sql
where ust_control_id = 23 and epa_table_name = 'ust_tank'
order by column_sort_order;

/*be sure to do select distinct if necessary!
NOTE: ADD facility_id::character varying(50)!!!!
NOTE: tank_id (integer) is a required field - if the state data does not contain an integer field
      that uniquely identifies the tank, you must generate one (see Compartments below for how to do this).
*/

drop table ok_ust.erg_tank;
create table ok_ust.erg_tank (facility_id int, tank_name  int,  tank_id int generated always as identity);
insert into ok_ust.erg_tank (facility_id,tank_name)
select  distinct "FacilityID", tank_name  from ok_ust."OK_UST_Data";

select  "FacilityID", tank_name  from ok_ust."OK_UST_Data" group by "FacilityID", tank_name having count(*) > 1;


select * from "erg_tank" where "facility_id"= 3884 and tank_name = 4;

drop view ok_ust.v_ust_tank;

create or replace view ok_ust.v_ust_tank as 
select distinct 
x."FacilityID"::character varying(50) as facility_id,
t."tank_id"::integer as tank_id,
x."tank_name"::character varying(50) as tank_name,
tank_status_id as tank_status_id,
case when "Manifold" is true then 'Yes' else 'No' end as multiple_tanks,
"ClosedDate"::date as tank_closure_date,
"InstalledDate"::date as tank_installation_date,
case when "Compartments" not in ('0','1') then 'Yes' else 'No' end as compartmentalized_ust,
"Compartments"::integer as number_of_compartments,
tank_material_description_id as tank_material_description_id,
tank_secondary_containment_id as tank_secondary_containment_id
from ok_ust."OK_UST_Data" x
join ok_ust.erg_tank t on x."FacilityID" = t.facility_id  and x.tank_name = t.tank_name
left join ok_ust.v_tank_status_xwalk vtsx on vtsx.organization_value = x."Status"
left join ok_ust.v_tank_material_description_xwalk vtmdx  on vtmdx.organization_value = x."Tank Material"
left join ok_ust.v_tank_secondary_containment_xwalk s  on s.organization_value = x."Tank Construction";

select distinct "Manifold" from "OK_UST_Data"

select * from v_ust_tank;
select count(*) from v_ust_tank; 
39909


--------------------------------------------------------------------------------------------------------------------------
--ust_compartment
select organization_table_name_qtd, organization_column_name_qtd,
	selected_column, data_type, character_maximum_length,
	programmer_comments, database_lookup_table, database_lookup_column,
	--organization_join_table_qtd, organization_join_column_qtd,
	deagg_table_name, deagg_column_name 
from v_ust_table_population_sql
where ust_control_id = 23 and epa_table_name = 'ust_compartment'
order by column_sort_order;

/* be sure to do select distinct if necessary!
NOTE: ADD facility_id::character varying(50) and tank_id::int!!!!
NOTE: compartment_id (integer) is a required field - if the state data does not contain an integer field
      that uniquely identifies the compartment, you must generate one. 
      In this case, the state does not store compartment data, so we will generate the compartment ID
      Prefix any tables you create in the state schema that did not come from the source data with "erg_"! */


drop table ok_ust.erg_compartment;
create table ok_ust.erg_compartment (facility_id int, tank_name  int, tank_id int,  compartment_id int generated always as identity);
insert into ok_ust.erg_compartment (facility_id,tank_name,tank_id)
select  distinct facility_id, tank_name,tank_id  from ok_ust.erg_tank;


create or replace view ok_ust.v_ust_compartment as 
select distinct 
t2."facility_id"::character varying(50) as facility_id,
t2.tank_id,
t2.compartment_id,
x."tank_name"::character varying(50) as compartment_name,
compartment_status_id as compartment_status_id,
"Capacity"::integer as compartment_capacity_gallons
from ok_ust."OK_UST_Data" x  
join ok_ust.erg_tank t on x."FacilityID" = t.facility_id  and x.tank_name = t.tank_name 
join ok_ust.erg_compartment t2 on t.facility_id = t2.facility_id  and t.tank_name = t2.tank_name  and t.tank_id = t2.tank_id 
left join ok_ust.v_compartment_status_xwalk vtsx on vtsx.organization_value = x."Status";


select count(*) from v_ust_compartment;
39909
select * from v_ust_compartment;



--------------------------------------------------------------------------------------------------------------------------

--QA/QC

--check that you didn't miss any columns when creating the data population views:
--if any rows are returned by this query, fix the appropriate view by adding the missing columns!
select epa_table_name, epa_column_name, 
	organization_table_name, organization_column_name, 
	organization_join_table, organization_join_column, 
	deagg_table_name, deagg_column_name
from v_ust_missing_view_mapping a
where ust_control_id = 23
order by 1, 2;

--run Python QA/QC script

/*run script qa_check.py
set variables:
ust_or_release = 'ust' 
control_id = 11
export_file_path = None # If export_file_path and export_file_dir/export_file_name are None, defaults to exporting to export directory of repo
export_file_dir = None	# If export_file_path and export_file_dir/export_file_name are None, defaults to exporting to export directory of repo
export_file_name = None	# If export_file_path and export_file_dir/export_file_name are None, defaults to exporting to export directory of repo

This script will check the views you just created in the state schema for the following:
1) Missing views - will check that if you created a child view (for example, v_ust_compartment), that the parent view(s) (for example, v_ust_tank)
   exist. 
2) Counts of child tables that have too few rows (for example, v_ust_compartment should have at least as many rows as v_ust_tank because
   every tank should have at least one compartment). 
3) Missing join columns to parent tables. For example, v_ust_compartment must contain facility_id and tank_id in order to be able to join it
   to its parent tables. 
4) Missing required columns. 
5) Required columns that exist but contain null values. 
6) Extraneous columns - will check for any columns in the views that don't match a column in the equivalent EPA table. This will help identify
   typos or other errors. 
7) Non-unique rows. To resolve any cases where the counts are greater than 0, check that you did a "select distinct" when creating these views.
   Then check for bad joins.  
8) Bad data types - will check for columns in the view where either the data type is different than the EPA column, or (for character columns) 
   if the length of the state value is too long to fit into the EPA column. If the data is too long to fit in the EPA column, this may indicate 
   an error in your code or mapping, OR it may mean you need to truncate the state's value to fit the EPA format. 
9) Failed check constraints. 
10) Bad mapping values. To resolve any cases where bad mapping values exist, examine the specific row(s) in public.ust_element_value_mapping 
   and ensure the epa_value exists in the associated lookup table. 

The script will also provide the counts of rows in ok_ust.v_ust_facility, ok_ust.v_ust_tank, ok_ust.v_ust_compartment, and
   ok_ust.v_ust_piping (if these views exist) - ensure these counts make sense! 
   
The script will export a QAQC spreadsheet (in additional to printing to the screen and logs). If there are errors, re-write the views above, 
then re-run the qa script, and proceed when all errors have been resolved. */



--------------------------------------------------------------------------------------------------------------------------
--insert data into the EPA schema 

/*run script populate_epa_data_tables.py	
set variables:
ust_or_release = 'ust' 
control_id = 11
delete_existing = False # can set to True if there is existing UST data you need to delete before inserting new
*/

--------------------------------------------------------------------------------------------------------------------------
--Quick sanity check of number of rows inserted:
select table_name, num_rows 
from v_ust_table_row_count
where ust_control_id = 23 
order by sort_order;
/*
ust_facility	13967
ust_tank	39909
ust_compartment	39909
*/


--------------------------------------------------------------------------------------------------------------------------
--export template

/*run script export_template.py
set variables:
control_id = 9
ust_or_release = 'ust' 
organization_id = None  	# Can leave as None if you specify the control_id
data_only = False 			# Set to False to export full template including mapping and reference tabs
template_only = False 		# Set to False to export data and mapping tabs as well as reference tab
export_file_path = None 	# If export_file_path and export_file_dir/export_file_name are None, defaults to exporting to export directory of repo
export_file_dir = None		# If export_file_path and export_file_dir/export_file_name are None, defaults to exporting to export directory of repo
export_file_name = None		# If export_file_path and export_file_dir/export_file_name are None, defaults to exporting to export directory of repo*/


--------------------------------------------------------------------------------------------------------------------------
--export control table  summary

/*run script control_table_summary.py
set variables:
control_id = 9
ust_or_release = 'ust' 
organization_id = None  	# Can leave as None if you specify the control_id
export_file_path = None 	# If export_file_path and export_file_dir/export_file_name are None, defaults to exporting to export directory of repo
export_file_dir = None		# If export_file_path and export_file_dir/export_file_name are None, defaults to exporting to export directory of repo
export_file_name = None		# If export_file_path and export_file_dir/export_file_name are None, defaults to exporting to export directory of repo*/

--------------------------------------------------------------------------------------------------------------------------



--------------------------------------------------------------------------------------------------------------------------

