CREATE TABLE as_ust.erg_as_ust_clean_cui (
    "FacilityID" text  NULL ,
    "FacilityName" text  NULL ,
    "FacilityName_cui" boolean  NULL ,
    "OwnerType" text  NULL ,
    "FacilityType1" text  NULL ,
    "FacilityType2" double precision  NULL ,
    "FacilityAddress1" text  NULL ,
    "FacilityAddress2" double precision  NULL ,
    "FacilityCity" text  NULL ,
    "FacilityCounty" text  NULL ,
    "FacilityZipCode" bigint  NULL ,
    "FacilityState" text  NULL ,
    "FacilityEPARegion" text  NULL ,
    "FacilityTribalSite" double precision  NULL ,
    "FacilityTribe" double precision  NULL ,
    "FacilityLatitude" text  NULL ,
    "FacilityLongitude" text  NULL ,
    "FacilityCoordinateSource" text  NULL ,
    "FacilityOwnerCompanyName" text  NULL ,
    "FacilityOperatorCompanyName" text  NULL ,
    "FinancialResponsibilityObtained" text  NULL ,
    "FinancialResponsibilityBondRatingTest" double precision  NULL ,
    "FinancialResponsibilityCommercialInsurance" double precision  NULL ,
    "FinancialResponsibilityGuarantee" double precision  NULL ,
    "FinancialResponsibilityLetterOfCredit" double precision  NULL ,
    "FinancialResponsibilityLocalGovernmentFinancialTest" double precision  NULL ,
    "FinancialResponsibilityRiskRetentionGroup" double precision  NULL ,
    "FinancialResponsibilitySelfInsuranceFinancialTest" double precision  NULL ,
    "FinancialResponsibilityStateFund" double precision  NULL ,
    "FinancialResponsibilitySuretyBond" double precision  NULL ,
    "FinancialResponsibilityTrustFund" double precision  NULL ,
    "FinancialResponsibilityOtherMethod" double precision  NULL ,
    "USTReportedRelease" double precision  NULL ,
    "AssociatedLUSTID" text  NULL ,
    "DispenserID" double precision  NULL ,
    "DispenserUDC" text  NULL ,
    "DispenserUDCWallType" text  NULL );