CREATE TABLE as_ust.ERG_Piping (
    "FacilityID" text  NULL ,
    "TankID" text  NULL ,
    "TankName" text  NULL ,
    "CompartmentID" double precision  NULL ,
    "CompartmentName" double precision  NULL ,
    "PipingID" text  NULL ,
    "PipingStyle" text  NULL ,
    "SafeSuction" text  NULL ,
    "AmericanSuction" text  NULL ,
    "HighPressureOrBulkPiping" text  NULL ,
    "PipingMaterialFRP" text  NULL ,
    "PipingMaterialGalSteel" text  NULL ,
    "PipingMaterialStainlessSteel" text  NULL ,
    "PipingMaterialSteel" text  NULL ,
    "PipingMaterialCopper" text  NULL ,
    "PipingMaterialFlex" text  NULL ,
    "PipingMaterialNoPiping" double precision  NULL ,
    "PipingMaterialOther" double precision  NULL ,
    "PipingMaterialUnknown" double precision  NULL ,
    "PipingFlexConnector" text  NULL ,
    "PipingCorrosionProtectionSacrificialAnode" double precision  NULL ,
    "PipingCorrosionProtectionImpressedCurrent" text  NULL ,
    "PipingCorrosionProtectionCathodicNotRequired" double precision  NULL ,
    "PipingCorrosionProtectionOther" double precision  NULL ,
    "PipingCorrosionProtectionUnknown" double precision  NULL ,
    "PipingLineLeakDetector" text  NULL ,
    "PipingAutomatedIntersticialMonitoring" double precision  NULL ,
    "PipingLineTestAnnual" text  NULL ,
    "PipingLineTest3yr" text  NULL ,
    "PipingGroundwaterMonitoring" double precision  NULL ,
    "PipingVaporMonitoring" double precision  NULL ,
    "PipingInterstitialMonitoring" double precision  NULL ,
    "PipingStatisticalInventoryReconciliation" double precision  NULL ,
    "PipingReleaseDetectionOther" text  NULL ,
    "PipingSubpartKLineTest" double precision  NULL ,
    "PipingSubpartKOther" double precision  NULL ,
    "PipeTankTopSump" text  NULL ,
    "PipeTankTopSumpWallType" text  NULL ,
    "PipingWallType" text  NULL ,
    "PipeTrenchLiner" double precision  NULL ,
    "PipeSecondaryContainmentOther" double precision  NULL ,
    "PipeSecondaryContainmentUnknown" double precision  NULL );