-- Clara Pitkins
-- clara.pitkins@erg.com
-- 11/18/24

-- Insert a new line into ust_control

insert into ust_control (organization_id, date_received, date_processed, data_source, organization_compartment_flag)
values ('HI', '2024-07-22', '2024-11-08', 'State submitted an Excel spreadsheet very close to EPA template format; 
will require specific value mapping. Contains additional data not in template.', 'N')
returning ust_control_id

-- populate the ust_element_mapping table

------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--Step 4: Map the source data elements to the EPA template elements 

/* Table public.ust_element_mapping documents the mapping of the source data elements
 * to the EPA template data elements. 
 * Go through each generated SQL statement and do the following:
 * 	1) If there is no matching column in the state's data, delete the SQL statement.
 *  2) If there is a matching column in the state's data, update the ORG_TAB_NAME
 *     and ORG_COL_NAME variables to match the state's data. 
 *  3) If you have questions or comments about the mapping, replace "null" with your 
 *     comment. 
 *  4) There should be only a one-to-one relationship between the EPA column and the
 *     source data column. If you need to use a combination of state columns to map
 *     to a single EPA column, create a crosswalk table (prefix the name of this table
 *     with "erg_" so it is obvious by glancing at the schema that we created it) that
 *     contains the primary key column(s) from the source data table (for example, 
 *     FacilityID or FacilityID and TankID, etc.) and then a column that performs 
 *     whatever manipulation you need to do to the data to transform it into a single
 *     column. Enter the table name and column name from the table you created into 
 *     ORG_TAB_NAME and ORG_COLUMN_NAME and describe in detail in programmer_comments
 *     what you did. 
 *  5) Also use the programmer_comments field to enter specifics about the mapping. 
 *     FOR EXAMPLE, say the source data has a single column for Financial Responsibility,
 *     in table "facilities" and column "fr_type", with a list of possible values like
 *     ["credit", "guarantee", "local gov't", "self insurance", "state fund", "other"]. 
 *     Map EPA fields financial_responsibility_obtained,
 * 	   financial_responsibility_letter_of_credit, financial_responsibility_guarantee,
 * 	   financial_responsibility_local_government_financial_test, 
 * 	   financial_responsibility_self_insurance_financial_test, and financial_responsibility_other_method
 *     ALL to state column "fr_type", and set the programmer_comments field as follows:
 *     financial_responsibility_obtained: "if not null then 'Yes'"	      
 * 	   financial_responsibility_letter_of_credit: "if = 'credit' then 'Yes'"	
 *     financial_responsibility_guarantee: "if = 'guarantee' then 'Yes'"	
 *     financial_responsibility_local_government_financial_test: "if = 'local gov't' then 'Yes'"	
 *     financial_responsibility_self_insurance_financial_test: "if = 'self insurance' then 'Yes'"	
 *     financial_responsibility_state_fund: "if = 'state fun' then 'Yes'"
 * 	   financial_responsibility_other_method: "if = 'state fund' then 'Yes'"	
 * After you've adjusted all the SQL statements for elements you are able to map and deleted those
 * you can't, run the SQL statements to perform the inserts.  
 * 
 * The SQL statements below were generated by running this query:
 
select * from public.v_ust_element_summary_sql;

 * It might help you to have another tab open in your database console where you can run queries like the 
 * following to help you do the mapping. FOR EXAMPLE, say you are trying to map EPA field facility_type1. 
 * This query may help you find it in the source data:

select table_name, column_name, data_type
from information_schema.columns 
where lower(table_schema) = 'XX_ust' 
and lower(column_name) like '%fac%type%'
order by 1, 2;

 * DO NOT assume that just because a state column name is very similar to or exactly the same as
 * an EPA column that they are the same thing. Before mapping a state element, run some queries to 
 * make sure it actually contains the right data:

--query the EPA lookup table to see what we are looking for, for example:
select * from public.facility_types order by 1;

--then see what the state's data looks like:
select distinct "ORG_COL_NAME"
from XX_ust."ORG_TAB_NAME"
order by 1;

 * If the states's values look approximately like EPA's values, it's OK to map. 

 * NOTE: 
 * The SQL statements below assume the state's data is in a relative flat format, e.g. there aren't
 * lookup tables. If the source data contains lookup tables, manipulate the SQL statements below to
 * include columns organization_join_table and organization_join_column. 
 * In this case, set the organization_table_name and organization_column_name to the source LOOKUP TABLE,
 * and set organization_join_table and organization_join_column to the source PARENT TABLE. 
 * For examples of how to do this, run this query:
 * 
select ust_control_id, epa_table_name, epa_column_name, 
	organization_table_name, organization_column_name,
	organization_join_table, organization_join_column
from public.ust_element_mapping
where organization_join_table is not null 
order by 1, 2, 3, 4, 5;

 * NOTE:
 * The SQL statements below also assume the state's data is stored with a single value per cell. 
 * Sometimes states stored multiple values in a single cell, separated by a comma or other separator (if you're lucky...)
 * When examining the state's data with this query:

select distinct "ORG_COL_NAME"
from XX_ust."ORG_TAB_NAME"
order by 1;

 * If some rows appear to contain multiple values, you will have to DEAGGREGATE the data. This is most easily done
 * using a Python script written for that purpose and is discussed in the next step. In this step, set the 
 * organization_table_name and organization_column_name to the source data table and column containing the 
 * multiple values. When you get to the next step where you are mapping the values and you run deagg.py to
 * perform the deaggregation, the script will update the deagg_table_name and deagg_column_name columns of
 * public.ust_element_mapping for you. The query below finds examples of how ust_element_mapping eventually gets 
 * populated for these fields. 

select ust_control_id, epa_table_name, epa_column_name, 
	organization_table_name, organization_column_name,
	deagg_table_name, deagg_column_name
from public.ust_element_mapping
where deagg_table_name is not null 
order by 1, 2, 3, 4, 5;

 */

--ust_facility: This table is REQUIRED
--NOTE: facility_id is a required field. If Facility ID does not exist in the source data, STOP and talk to the state. 
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments)
values (24,'ust_facility','facility_name','facility','FacilityName',null); 
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_facility','owner_type_id','facility','OwnerType',null); -- HI dataset does not have the information as the id, and has it as text
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_facility','facility_type1','facility','FacilityType1',null);-- HI dataset does not have the information as the id, and has it as text
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_facility','facility_address1','facility','FacilityAddress1',null);
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_facility','facility_address2','facility','FacilityAddress2',null);
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_facility','facility_city','facility','FacilityCity',null);
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_facility','facility_county','facility','FacilityCounty',null);
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_facility','facility_zip_code','facility','FacilityZipCode',null);
--NOTE: facility_state is a required field but is not always populated in the state's data because the
--source database may assume all facilities are in the state. This column will be added to the v_ust_facility view 
--in a later step if it is not mapped here
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_facility','facility_state','facility','FacilityState',null);
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_facility','facility_latitude','facility','LatitudeMeasure',null);
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_facility','facility_longitude','facility','LongitudeMeasure',null);
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_facility','coordinate_source_id','facility','HorizontalCollectionMethodName',null); -- HI dataset does not have the information in the correct format for the lookup table
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_facility','facility_owner_company_name','facility','FacilityOwnerCompanyName',null);
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_facility','financial_responsibility_obtained','facility','FinancialResponsibilityObtained',null);
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_facility','associated_ust_release_id','facility','AssociatedLUSTID',null);

--ust_tank: This table is REQUIRED.
--At a mimimum we need a Tank ID (or Tank Name) and Tank Status. If these fields don't exist in the source data, stop and talk to EPA and/or the state. 
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_tank','facility_id','tank','FacilityID',null);
--NOTE: Tank ID is required, but we can create it in a later step as long as Tank Name exists in the source data.
--Tank ID must be an INTEGER (or able to be converted to an integer). 
--If the source data contains a column called Tank ID but it contains alphanumeric values, map it to EPA column tank_name instead of tank_id.
--NOTE: Either tank_id or tank_name (or both) must be mapped. Use tank_id for numeric fields and tank_name for alphanumeric/text fields. 
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_tank','tank_name','tank','TankID',null);
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_tank','tank_status_id','tank','TankStatus',null); --information is not in the correct format for lookup table
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_tank','federally_regulated','tank','FederallyRegulated',null); -- t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_tank','field_constructed','tank','FieldConstructed',null); -- t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_tank','emergency_generator','tank','EmergencyGenerator',null); -- t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_tank','airport_hydrant_system','tank','AirportHydrantSystem',null); -- for some reason a float? instead of a bool or y/n
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_tank','multiple_tanks','tank','MultipleTanks',null); -- t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_tank','tank_closure_date','tank','TankClosureDate',null);
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_tank','tank_installation_date','tank','TankInstallationDate',null);
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_tank','compartmentalized_ust','tank','CompartmentalizedUST',null); -- t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_tank','tank_material_description_id','tank','TankMaterialDescription',null); -- format needs to be changed for lookup table
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_tank','tank_corrosion_protection_sacrificial_anode','tank','TankCorrosionProtectionSacrificialAnode',null); -- t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_tank','tank_corrosion_protection_impressed_current','tank','TankCorrosionProtectionImpressedCurrent',null); --t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_tank','tank_corrosion_protection_cathodic_not_required','tank','TankCorrosionProtectionCathodicNotRequired',null); --t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_tank','tank_corrosion_protection_interior_lining','tank','TankCorrosionProtectionInteriorLining',null); -- t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_tank','tank_secondary_containment_id','tank','TankSecondaryContainment',null); -- format needs to be changed for lookup table

--ust_tank_substance: This table is OPTIONAL (but most states will have data) -- I do not think HI has this data

--NOTE: States that report at the compartment level will likely have substance data at the compartment level
--This will be tracked in table ust_compartment_substance, but all of the columns in that table will be mapped elsewhere
--so there is no mapping required for that table. 

--ust_compartment: This table is REQUIRED. 
--If the state does not report compartment data, we will be creating a Compartment ID for it in a later step. 
--Look for these data elements in the tank data for states that don't report compartments. 
--Compartment Status is required; copy the Tank Status mapping for Compartment Status data for states 
--that don't report compartments or do report compartments but don't have a separate compartment status. 
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_compartment','facility_id','compartment','FacilityID',null);
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_compartment','tank_name','compartment','TankID',null);
--NOTE: Compartment ID must be an INTEGER (or able to be converted to an integer). 
--NOTE: Compartment Status is a required field. If the state does not report compartments, use the same element mapping as Tank Status
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_compartment','compartment_status_id','tank','TankStatus',null); --is this right? also needs to be updated for the lookup table
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_compartment','overfill_prevention_ball_float_valve','compartment','OverfillPreventionBallFloatValve',null); -- t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_compartment','overfill_prevention_flow_shutoff_device','compartment','OverfillPreventionFlowShutoffDevice',null); --t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_compartment','overfill_prevention_high_level_alarm','compartment','OverfillPreventionHighLevelAlarm',null); --t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_compartment','spill_bucket_installed','compartment','SpillBucketInstalled',null);
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_compartment','tank_interstitial_monitoring','compartment','TankInterstitialMonitoring',null); -- t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_compartment','tank_automatic_tank_gauging_release_detection','compartment','TankAutomaticTankGaugingReleaseDetection',null); --t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_compartment','tank_manual_tank_gauging','compartment','TankManualTankGauging',null); -- t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_compartment','tank_statistical_inventory_reconciliation','compartment','TankStatisticalInventoryReconciliation',null); --t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_compartment','tank_tightness_testing','compartment','TankTightnessTesting',null); -- t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_compartment','tank_inventory_control','compartment','TankInventoryControl',null); -- t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_compartment','tank_groundwater_monitoring','compartment','TankGroundwaterMonitoring',null); -- t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_compartment','tank_vapor_monitoring','compartment','TankVaporMonitoring',null); -- t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_compartment','tank_other_release_detection','compartment','TankOtherReleaseDetection',null); --t/f to y/n needed

--ust_piping: This table is OPTIONAL, do not map if there is no piping data in the source data
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_piping','facility_id','piping','FacilityID',null);
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_piping','tank_name','piping','TankID',null);
--NOTE: Piping ID is a required field but if there is no INTEGER field in the source data that uniquely identifies each
--piping run per Facility/Tank (non-compartment states) or Facility/Tank/Compartment (compartment states),
--we will be constructing a Piping ID in a later step so don't map it now.
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_piping','piping_style_id','piping','PipingStyle',null); -- lookup table
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_piping','piping_corrosion_protection_sacrificial_anode','piping','PipingCorrosionProtectionSacrificialAnode',null); --t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_piping','piping_corrosion_protection_impressed_current','piping','PipingCorrosionProtectionImpressedCurrent',null); --t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_piping','piping_line_leak_detector','piping','PipingLineLeakDetector',null); -- t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_piping','piping_line_test_annual','piping','PipingLineTestAnnual',null); --t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_piping','piping_groundwater_monitoring','piping','PipingGroundwaterMonitoring',null); --t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_piping','piping_vapor_monitoring','piping','PipingVaporMonitoring',null); --t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_piping','piping_statistical_inventory_reconciliation','piping','PipingStatisticalInventoryReconciliation',null); --t/f to y/n needed
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_piping','piping_release_detection_other','piping','PipingReleaseDetectionOther',null); --t/f to y/n needed

--ust_facility_dispenser: Map and populate this table only if the state stores dispenser data at the Facility level.
--Dispenser data is OPTIONAL.
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_facility_dispenser','facility_id','dispenser','FacilityID',null);
insert into public.ust_element_mapping (ust_control_id, epa_table_name, epa_column_name, organization_table_name, organization_column_name, programmer_comments) 
values (24,'ust_facility_dispenser','dispenser_id','dispenser','DispenserID',null);

