CREATE TABLE in_ust.erg_in_ust_clean_cui (
    "﻿FacilityID" text  NULL ,
    "FacilityName" text  NULL ,
    "FacilityName_cui" double precision  NULL ,
    "OwnerType" text  NULL ,
    "FacilityType1" text  NULL ,
    "FacilityType2" text  NULL ,
    "FacilityAddress1" text  NULL ,
    "FacilityAddress2" text  NULL ,
    "FacilityCity" text  NULL ,
    "FacilityCounty" text  NULL ,
    "FacilityZipCode" text  NULL ,
    "FacilityState" text  NULL ,
    "FacilityEPARegion" double precision  NULL ,
    "FacilityTribalSite" text  NULL ,
    "FacilityLatitude" double precision  NULL ,
    "FacilityLongitude" double precision  NULL ,
    "FacilityCoordinateSource" text  NULL ,
    "FacilityOwnerCompanyName" text  NULL ,
    "FacilityOperatorCompanyName" text  NULL ,
    "FinancialResponsibilityObtained" text  NULL ,
    "FinancialResponsibilityBondRatingTest" double precision  NULL ,
    "FinancialResponsibilityCommercialInsurance" text  NULL ,
    "FinancialResponsibilityGuarantee" text  NULL ,
    "FinancialResponsibilityLetterOfCredit" text  NULL ,
    "FinancialResponsibilityLocalGovernmentFinancialTest" text  NULL ,
    "FinancialResponsibilityRiskRetentionGroup" text  NULL ,
    "FinancialResponsibilitySelfInsuranceFinancialTest" text  NULL ,
    "FinancialResponsibilityStateFund" text  NULL ,
    "FinancialResponsibilitySuretyBond" text  NULL ,
    "FinancialResponsibilityTrustFund" text  NULL ,
    "FinancialResponsibilityOtherMethod" text  NULL ,
    "USTReportedRelease" text  NULL ,
    "AssociatedLUSTID" double precision  NULL );