CREATE TABLE public.chemical_list (
    dtxsid text  NULL ,
    preferred_name text  NULL ,
    casrn text  NULL ,
    inchikey text  NULL ,
    iupac_name text  NULL ,
    smiles text  NULL ,
    inchi_string text  NULL ,
    molecular_formula text  NULL ,
    average_mass double precision  NULL ,
    monoisotopic_mass text  NULL ,
    qc_level bigint  NULL ,
    num_toxcast_active text  NULL ,
    total_assays double precision  NULL ,
    percent_toxcast_active double precision  NULL );