CREATE TABLE public.release_elements (
    element_id integer  NOT NULL generated always as identity,
    element_name character varying(200)  NULL ,
    element_description character varying(4000)  NULL ,
    displayed_in_ustfinder character varying(1)  NULL ,
    element_type character varying(20)  NULL ,
    element_size integer  NULL ,
    required character varying(20)  NULL ,
    allowed_values character varying(1)  NULL ,
    lookup_table character varying(50)  NULL ,
    business_rule character varying(4000)  NULL ,
    notes character varying(4000)  NULL ,
    database_column_name character varying(100)  NULL ,
    database_lookup_table character varying(100)  NULL ,
    database_lookup_column character varying(100)  NULL );