CREATE TABLE public.ust_compartment (
    ust_compartment_id integer  NOT NULL generated always as identity,
    ust_tank_id integer  NULL ,
    compartment_id integer  NULL ,
    compartment_name character varying(50)  NULL ,
    compartment_status_id integer  NOT NULL ,
    substance_id integer  NULL ,
    compartment_substance_casno character varying(12)  NULL ,
    compartment_capacity_gallons integer  NULL ,
    overfill_prevention_ball_float_valve character varying(7)  NULL ,
    overfill_prevention_flow_shutoff_device character varying(7)  NULL ,
    overfill_prevention_high_level_alarm character varying(7)  NULL ,
    overfill_prevention_other character varying(7)  NULL ,
    overfill_prevention_unknown character varying(7)  NULL ,
    overfill_prevention_not_required character varying(7)  NULL ,
    spill_bucket_installed character varying(3)  NULL ,
    concrete_berm_installed character varying(3)  NULL ,
    spill_prevention_other character varying(3)  NULL ,
    spill_prevention_not_required character varying(3)  NULL ,
    spill_bucket_wall_type_id integer  NULL ,
    tank_interstitial_monitoring character varying(7)  NULL ,
    tank_automatic_tank_gauging_release_detection character varying(7)  NULL ,
    automatic_tank_gauging_continuous_leak_detection character varying(7)  NULL ,
    tank_manual_tank_gauging character varying(7)  NULL ,
    tank_statistical_inventory_reconciliation character varying(7)  NULL ,
    tank_tightness_testing character varying(7)  NULL ,
    tank_inventory_control character varying(7)  NULL ,
    tank_groundwater_monitoring character varying(7)  NULL ,
    tank_vapor_monitoring character varying(7)  NULL ,
    tank_subpart_k_tightness_testing character varying(7)  NULL ,
    tank_subpart_k_other character varying(7)  NULL ,
    tank_other_release_detection character varying(7)  NULL ,
    dispenser_id character varying(50)  NULL ,
    dispenser_udc character varying(7)  NULL ,
    dispenser_udc_wall_type_id integer  NULL );