CREATE TABLE public.ust_piping (
    ust_piping_id integer  NOT NULL generated always as identity,
    ust_compartment_id integer  NULL ,
    piping_id character varying(50)  NULL ,
    piping_style_id integer  NULL ,
    safe_suction character varying(7)  NULL ,
    american_suction character varying(7)  NULL ,
    high_pressure_or_bulk_piping character varying(7)  NULL ,
    piping_material_frp character varying(3)  NULL ,
    piping_material_gal_steel character varying(3)  NULL ,
    piping_material_stainless_steel character varying(3)  NULL ,
    piping_material_steel character varying(3)  NULL ,
    piping_material_copper character varying(3)  NULL ,
    piping_material_flex character varying(3)  NULL ,
    piping_material_no_piping character varying(3)  NULL ,
    piping_material_other character varying(3)  NULL ,
    piping_material_unknown character varying(3)  NULL ,
    piping_flex_connector character varying(7)  NULL ,
    piping_corrosion_protection_sacrificial_anode character varying(7)  NULL ,
    piping_corrosion_protection_impressed_current character varying(7)  NULL ,
    piping_corrosion_protection_cathodic_not_required character varying(7)  NULL ,
    piping_corrosion_protection_other character varying(7)  NULL ,
    piping_corrosion_protection_unknown character varying(7)  NULL ,
    piping_line_leak_detector character varying(7)  NULL ,
    piping_automated_intersticial_monitoring character varying(7)  NULL ,
    piping_line_test_annual character varying(7)  NULL ,
    piping_line_test3yr character varying(7)  NULL ,
    piping_groundwater_monitoring character varying(7)  NULL ,
    piping_vapor_monitoring character varying(7)  NULL ,
    piping_interstitial_monitoring character varying(7)  NULL ,
    piping_statistical_inventory_reconciliation character varying(7)  NULL ,
    piping_release_detection_other character varying(7)  NULL ,
    piping_subpart_k_line_test character varying(7)  NULL ,
    piping_subpart_k_other character varying(7)  NULL ,
    pipe_tank_top_sump character varying(7)  NULL ,
    pipe_tank_top_sump_wall_type_id integer  NULL ,
    piping_wall_type_id integer  NULL ,
    pipe_trench_liner character varying(7)  NULL ,
    pipe_secondary_containment_other character varying(7)  NULL ,
    pipe_secondary_containment_unknown character varying(7)  NULL );