CREATE TABLE public.ust_facility (
    ust_facility_id integer  NOT NULL generated always as identity,
    facility_id character varying(50)  NOT NULL ,
    facility_name character varying(100)  NULL ,
    owner_type_id integer  NULL ,
    facility_type1 integer  NULL ,
    facility_type2 integer  NULL ,
    facility_address1 character varying(100)  NULL ,
    facility_address2 character varying(100)  NULL ,
    facility_city character varying(100)  NULL ,
    facility_county character varying(100)  NULL ,
    facility_zip_code character varying(10)  NULL ,
    facility_state character varying(2)  NOT NULL ,
    facility_epa_region integer  NULL ,
    facility_tribal_site character varying(3)  NULL ,
    facility_tribe character varying(200)  NULL ,
    facility_latitude double precision  NULL ,
    facility_longitude double precision  NULL ,
    coordinate_source_id integer  NULL ,
    facility_owner_company_name character varying(100)  NULL ,
    facility_operator_company_name character varying(100)  NULL ,
    financial_responsibility_obtained character varying(7)  NULL ,
    financial_responsibility_bond_rating_test character varying(3)  NULL ,
    financial_responsibility_commercial_insurance character varying(3)  NULL ,
    financial_responsibility_guarantee character varying(3)  NULL ,
    financial_responsibility_letter_of_credit character varying(3)  NULL ,
    financial_responsibility_local_government_financial_test character varying(3)  NULL ,
    financial_responsibility_risk_retention_group character varying(3)  NULL ,
    financial_responsibility_self_insurance_financial_test character varying(3)  NULL ,
    financial_responsibility_state_fund character varying(3)  NULL ,
    financial_responsibility_surety_bond character varying(3)  NULL ,
    financial_responsibility_trust_fund character varying(3)  NULL ,
    financial_responsibility_other_method character varying(500)  NULL ,
    ust_reported_release character varying(7)  NULL ,
    associated_ust_release_id character varying(40)  NULL ,
    dispenser_id character varying(50)  NULL ,
    dispenser_udc character varying(7)  NULL ,
    dispenser_udc_wall_type_id integer  NULL ,
    ust_control_id integer  NULL );