CREATE TABLE public.ust_tank (
    ust_tank_id integer  NOT NULL generated always as identity,
    ust_facility_id integer  NOT NULL ,
    tank_id integer  NOT NULL ,
    tank_name character varying(50)  NULL ,
    tank_location_id integer  NULL ,
    tank_status_id integer  NOT NULL ,
    federally_regulated character varying(7)  NULL ,
    field_constructed character varying(7)  NULL ,
    emergency_generator character varying(7)  NULL ,
    airport_hydrant_system character varying(7)  NULL ,
    multiple_tanks character varying(7)  NULL ,
    tank_closure_date date  NULL ,
    tank_installation_date date  NULL ,
    compartmentalized_ust character varying(7)  NULL ,
    number_of_compartments integer  NULL ,
    tank_material_description_id integer  NULL ,
    tank_corrosion_protection_sacrificial_anode character varying(7)  NULL ,
    tank_corrosion_protection_impressed_current character varying(7)  NULL ,
    tank_corrosion_protection_cathodic_not_required character varying(7)  NULL ,
    tank_corrosion_protection_interior_lining character varying(7)  NULL ,
    tank_corrosion_protection_other character varying(7)  NULL ,
    tank_corrosion_protection_unknown character varying(7)  NULL ,
    tank_secondary_containment_id integer  NULL ,
    cert_of_installation_id integer  NULL ,
    cert_of_installation_other character varying(1000)  NULL ,
    dispenser_id character varying(50)  NULL ,
    dispenser_udc character varying(7)  NULL ,
    dispenser_udc_wall_type_id integer  NULL );