CREATE TABLE public.ust_release (
    ust_release_id integer  NOT NULL generated always as identity,
    facility_id character varying(50)  NULL ,
    tank_id_associated_with_release character varying(50)  NULL ,
    release_id character varying(50)  NOT NULL ,
    federally_reportable_release character varying(7)  NULL ,
    site_name character varying(200)  NULL ,
    site_address character varying(100)  NULL ,
    site_address2 character varying(100)  NULL ,
    site_city character varying(100)  NULL ,
    zipcode character varying(10)  NULL ,
    county character varying(100)  NULL ,
    state character varying(2)  NULL ,
    epa_region integer  NULL ,
    facility_type_id integer  NULL ,
    tribal_site character varying(7)  NULL ,
    tribe character varying(50)  NULL ,
    latitude double precision  NULL ,
    longitude double precision  NULL ,
    coordinate_source_id integer  NULL ,
    release_status_id integer  NOT NULL ,
    reported_date date  NULL ,
    nfa_date date  NULL ,
    media_impacted_soil character varying(3)  NULL ,
    media_impacted_groundwater character varying(3)  NULL ,
    media_impacted_surface_water character varying(3)  NULL ,
    how_release_detected_id integer  NULL ,
    closed_with_contamination character varying(7)  NULL ,
    no_further_action_letter_url character varying(2000)  NULL ,
    military_dod_site character varying(7)  NULL ,
    release_control_id integer  NOT NULL );