select 'null as "' || element_name || '",' from ust_elements order by element_position ;

select * from "TN_UST"."TN_UST_template" ;

create view "TN_UST".v_ust as
select 
	"FacilityID",
	"FacilityName",
	null as "OwnerType",
	"FacilityType" as "FacilityType1",
	null as "FacilityType2",
	"FacilityAddress1",
	"FacilityAddress2",
	"FacilityCity",
	null as "FacilityCounty",
	null as "FacilityZipCode",
	null as "FacilityPhoneNumber",
	"FacilityState",
	"FacilityEPARegion",
	null as "FacilityTribalSite",
	null as "FacilityTribe",
	"FacilityLatitude",
	"FacilityLongitude",
	null as "FacilityCoordinateSource",
	null as "FacilityOwnerCompanyName",
	null as "FacilityOwnerLastName",
	null as "FacilityOwnerFirstName",
	null as "FacilityOwnerAddress1",
	null as "FacilityOwnerAddress2",
	null as "FacilityOwnerCity",
	null as "FacilityOwnerCounty",
	null as "FacilityOwnerZipCode",
	null as "FacilityOwnerState",
	null as "FacilityOwnerPhoneNumber",
	null as "FacilityOwnerEmail",
	null as "FacilityOperatorCompanyName",
	null as "FacilityOperatorLastName",
	null as "FacilityOperatorFirstName",
	null as "FacilityOperatorAddress1",
	null as "FacilityOperatorAddress2",
	null as "FacilityOperatorCity",
	null as "FacilityOperatorCounty",
	null as "FacilityOperatorZipCode",
	null as "FacilityOperatorState",
	null as "FacilityOperatorPhoneNumber",
	null as "FacilityOperatorEmail",
	null as "FinancialResponsibilityBondRatingTest",
	null as "FinancialResponsibilityCommercialInsurance",
	null as "FinancialResponsibilityGuarantee",
	null as "FinancialResponsibilityLetterOfCredit",
	null as "FinancialResponsibilityLocalGovernmentFinancialTest",
	null as "FinancialResponsibilityRiskRetentionGroup",
	null as "FinancialResponsibilitySelfInsuranceFinancialTest",
	null as "FinancialResponsibilityStateFund",
	null as "FinancialResponsibilitySuretyBond",
	null as "FinancialResponsibilityTrustFund",
	null as "FinancialResponsibilityOtherMethod",
	null as "FinancialResponsibilityNotRequired",
	null as "FinancialResponsibilityObtained",
	null as "Compliance",
	"TankID",
	null as "TankLocation",
	null as "FederallyRegulated",
	"TankStatus",
	null as "FieldConstructed",
	null as "EmergencyGenerator",
	null as "AirportHydrantSystem",
	"MultipleTanks",
	"ClosureDate",
	"InstallationDate",
	"CompartmentalizedUST",
	"NumberofCompartments",
	null as "TankSubstanceStored",
	"CompartmentID",
	"CompartmentSubstanceStored",
	null as "TankCapacityGallons",
	"CompartmentCapacityGallons",
	null as "LinedTank",
	null as "ExcavationLiner",
	"TankWallType",
	"MaterialDescription",
	null as "TankRepaired",
	null as "TankRepairDate",
	null as "CertofInstallation",
	"PipingMaterialDescription",
	null as "PipingFlexConnector",
	null as "PipingStyle",
	null as "PipingWallType",
	null as "PipingUDCForEveryDispenser",
	null as "PipingRepaired",
	null as "PipingRepairDate",
	"TankCorrosionProtectionSacrificialAnode",
	"TankCorrosionProtectionAnodesInstalledOrRetrofitted",
	"TankCorrosionProtectionImpressedCurrent",
	"TankCorrosionProtectionImpressedCurrentInstalledOrRetrofitted",
	null as "TankCorrosionProtectionCathodicNotRequired",
	null as "TankCorrosionProtectionInteriorLining",
	null as "TankCorrosionProtectionOther",
	null as "TankCorrosionProtectionUnknown",
	null as "TankCorrosionProtectionLinedPostinstallation",
	"PipingCorrosionProtectionSacrificialAnode" as "PipingCorrosionProtectionSacrificialAnodes",
	"PipingCorrosionProtectionAnodesInstalledOrRetrofitted",
	"PipingCorrosionProtectionImpressedCurrent",
	"PipingCorrosionProtectionImpressedCurrentInstalledOrRetrofitted",
	null as "PipingCorrosionProtectionCathodicNotRequired",
	null as "PipingCorrosionProtectionExternalCoating",
	null as "PipingCorrosionProtectionOther",
	null as "PipingCorrosionProtectionUnknown",
	null as "BallFloatValve",
	"AutomaticShutoffDevice" as "FlowShutoffDevice",
	"OverfillAlarm" as "HighLevelAlarm",
	"OverfillProtectionMeans" as "OverfillProtectionPrimary",
	null as "OverfillProtectionSecondary",
	null as "PrimaryOverfillInstallDate",
	null as "SecondaryOverfillInstallDate",
	"SpillBucketInstalled",
	null as "SpillBucketWallType",
	null as "DrainPresent",
	null as "PumpPresent",
	null as "InterstitialMonitoringContinualElectric",
	null as "InterstitialMonitoringManual",
	"AutomaticTankGauging",
	"AutomaticTankGaugingReleaseDetection",
	"AutomaticTankGaugingContinuousLeakDetection",
	"ManualTankGauging",
	"StatisticalInventoryReconciliation",
	"TankTightnessTesting",
	"GroundwaterMonitoring",
	null as "SubpartK",
	"VaporMonitoring",
	"ElectronicLineLeakDetector" as "ElectronicLineLeak",
	"MechanicalLineLeakDetector" as "MechanicalLineLeak",
	null as "AutomatedIntersticialMonitoring",
	"SafeSuction",
	"AmericanSafeSuction" as "AmericanSuction",
	null as "PipingSubpartK",
	null as "HighPressure",
	"PrimaryReleaseDetectionType",
	null as "SecondReleaseDetectionType",
	null as "PipeSecondaryContainment",
	null as "PipeInstallDate",
	null as "USTReportedRelease",
	null as "AssociatedLUSTID",
	null as "LastInspectionDate"
from "TN_UST"."TN_UST_template"; 

select * from "TN_UST".v_ust order by "FacilityID", "TankID";