CREATE TABLE az_ust.erg_ust_facility_clean_cui (
    "FacilityID" text  NULL ,
    "FacilityName" text  NULL ,
    "FacilityName_cui" character varying(20)  NULL ,
    "OwnerType" text  NULL ,
    "FacilityType1" text  NULL ,
    "FacilityType2" double precision  NULL ,
    "FacilityAddress1" text  NULL ,
    "FacilityAddress2" double precision  NULL ,
    "FacilityCity" text  NULL ,
    "FacilityCounty" text  NULL ,
    "FacilityZipCode" double precision  NULL ,
    "FacilityState" text  NULL ,
    "FacilityEPARegion" bigint  NULL ,
    "FacilityTribalSite" text  NULL ,
    "FacilityTribe" double precision  NULL ,
    "FacilityLatitude" double precision  NULL ,
    "FacilityLongitude" double precision  NULL ,
    "FacilityCoordinateSource" double precision  NULL ,
    "FacilityOwnerCompanyName" text  NULL ,
    "FacilityOperatorCompanyName" text  NULL ,
    "FinancialResponsibilityObtained" text  NULL ,
    "FinancialResponsibilityBondRatingTest" text  NULL ,
    "FinancialResponsibilityCommercialInsurance" text  NULL ,
    "FinancialResponsibilityGuarantee" text  NULL ,
    "FinancialResponsibilityLetterOfCredit" text  NULL ,
    "FinancialResponsibilityLocalGovernmentFinancialTest" text  NULL ,
    "FinancialResponsibilityRiskRetentionGroup" text  NULL ,
    "FinancialResponsibilitySelfInsuranceFinancialTest" text  NULL ,
    "FinancialResponsibilityStateFund" text  NULL ,
    "FinancialResponsibilitySuretyBond" text  NULL ,
    "FinancialResponsibilityTrustFund" text  NULL ,
    "FinancialResponsibilityOtherMethod" text  NULL ,
    "USTReportedRelease" double precision  NULL ,
    "AssociatedLUSTID" double precision  NULL ,
    "DispenserID" double precision  NULL ,
    "DispenserUDC" double precision  NULL ,
    "DispenserUDCWallType" double precision  NULL );