create or replace view "az_ust"."v_ust_facility" as
 SELECT DISTINCT (x."FacilityID")::character varying(50) AS facility_id,
    (x."FacilityName")::character varying(100) AS facility_name,
    ot.owner_type_id,
    (x."FacilityAddress1")::character varying(100) AS facility_address1,
    (x."FacilityCity")::character varying(100) AS facility_city,
    (x."FacilityCounty")::character varying(100) AS facility_county,
    (x."FacilityZipCode")::character varying(10) AS facility_zip_code,
    x."FacilityState" AS facility_state,
    (x."FacilityEPARegion")::integer AS facility_epa_region,
    (x."FacilityTribalSite")::character varying(3) AS facility_tribal_site,
    x."FacilityLatitude" AS facility_latitude,
    x."FacilityLongitude" AS facility_longitude,
    (x."FacilityOwnerCompanyName")::character varying(100) AS facility_owner_company_name,
    (x."FacilityOperatorCompanyName")::character varying(100) AS facility_operator_company_name,
    (x."FinancialResponsibilityObtained")::character varying(7) AS financial_responsibility_obtained,
    (x."FinancialResponsibilityBondRatingTest")::character varying(3) AS financial_responsibility_bond_rating_test,
    (x."FinancialResponsibilityCommercialInsurance")::character varying(3) AS financial_responsibility_commercial_insurance,
    (x."FinancialResponsibilityGuarantee")::character varying(3) AS financial_responsibility_guarantee,
    (x."FinancialResponsibilityLetterOfCredit")::character varying(3) AS financial_responsibility_letter_of_credit,
    (x."FinancialResponsibilityLocalGovernmentFinancialTest")::character varying(3) AS financial_responsibility_local_government_financial_test,
    (x."FinancialResponsibilityRiskRetentionGroup")::character varying(3) AS financial_responsibility_risk_retention_group,
    (x."FinancialResponsibilitySelfInsuranceFinancialTest")::character varying(3) AS financial_responsibility_self_insurance_financial_test,
    (x."FinancialResponsibilityStateFund")::character varying(3) AS financial_responsibility_state_fund,
    (x."FinancialResponsibilitySuretyBond")::character varying(3) AS financial_responsibility_surety_bond,
    (x."FinancialResponsibilityTrustFund")::character varying(3) AS financial_responsibility_trust_fund,
    (x."FinancialResponsibilityOtherMethod")::character varying(500) AS financial_responsibility_other_method
   FROM (az_ust.ust_facility x
     LEFT JOIN az_ust.v_owner_type_xwalk ot ON ((x."OwnerType" = (ot.organization_value)::text)));