"""Exact, read-only PostgreSQL counts for a portable migration baseline."""

import csv
import re
from contextlib import closing
from datetime import UTC, datetime
from pathlib import Path

import psycopg2
from psycopg2 import sql

from ust.python.util import config

FIELDS = ['schema', 'table', 'row_count', 'captured_at_utc', 'database',
          'baseline_count', 'difference', 'status']
DEFAULT_BASELINE = Path(__file__).resolve().parents[3] / 'old-db-counts.csv'


def important_table(name):
    """Exclude temp/backup name tokens, including markers followed by dates."""
    return not re.search(
        r'(^|[^a-z0-9])(temporary|temp|tmp|backup|backups|bkup|bkp|bak)(?=[^a-z]|$)',
        name, re.IGNORECASE,
    )


def read_baseline(path):
    counts = {}
    with Path(path).open(encoding='utf-8-sig', newline='') as source:
        reader = csv.DictReader(source)
        if not set(FIELDS).issubset(reader.fieldnames or []):
            raise ValueError('Baseline must be a CSV generated by ust db-counts.')
        for row in reader:
            name = row['table']
            if row['schema'] != 'public' or not important_table(name) or name in counts:
                raise ValueError('Baseline contains an unexpected or duplicate table.')
            if row['status'] != 'BASELINE':
                raise ValueError('Use the original baseline CSV, not a comparison report.')
            try:
                count = int(row['row_count'])
            except (ValueError, TypeError) as exc:
                raise ValueError('Baseline contains an invalid row count.') from exc
            if count < 0:
                raise ValueError('Baseline contains a negative row count.')
            counts[name] = count
    if not counts:
        raise ValueError('Baseline contains no included public tables.')
    return counts


def collect_counts():
    """Use one consistent snapshot; fail rather than silently count RLS-filtered rows."""
    required = ('db_ip', 'db_name', 'db_user', 'db_password')
    missing = ['UST_' + name.upper() for name in required if not getattr(config, name)]
    if missing:
        raise ValueError('Missing settings: ' + ', '.join(missing))
    with closing(psycopg2.connect(
        host=config.db_ip, dbname=config.db_name, user=config.db_user,
        password=config.db_password, port=5432, connect_timeout=10,
    )) as connection:
        connection.set_session(isolation_level='REPEATABLE READ', readonly=True)
        with connection.cursor() as cursor:
            cursor.execute("SET LOCAL statement_timeout = '10min'")
            cursor.execute("SET LOCAL lock_timeout = '10s'")
            cursor.execute('SET LOCAL row_security = off')
            cursor.execute("""
                SELECT c.relname
                FROM pg_catalog.pg_class c
                JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p')
                  AND NOT c.relispartition
                ORDER BY c.relname
            """)
            tables = [row[0] for row in cursor.fetchall() if important_table(row[0])]
            captured_at = datetime.now(UTC).isoformat()
            counts = {}
            for name in tables:
                print(f'  Counting public.{name}...', flush=True)
                cursor.execute(sql.SQL('SELECT COUNT(*) FROM {}.{}').format(
                    sql.Identifier('public'), sql.Identifier(name),
                ))
                counts[name] = cursor.fetchone()[0]
    return counts, captured_at


def report_rows(counts, captured_at, baseline=None):
    names = set(counts) | (set(baseline) if baseline is not None else set())
    rows = []
    for name in sorted(names):
        current = counts.get(name)
        previous = baseline.get(name) if baseline is not None else None
        if current is None:
            status = 'MISSING TABLE'
        elif baseline is None:
            status = 'BASELINE'
        elif previous is None:
            status = 'NEW TABLE'
        else:
            status = 'MATCH' if current == previous else 'MISMATCH'
        rows.append(dict(zip(FIELDS, [
            'public', name, current, captured_at, config.db_name, previous,
            current - previous if current is not None and previous is not None else None, status,
        ], strict=True)))
    return rows


def run(output, compare=None):
    output = Path(output).expanduser()
    try:
        if output.exists():
            raise ValueError('Output already exists; choose a new filename to preserve previous counts.')
        if not output.parent.is_dir():
            raise ValueError('Output directory does not exist.')
        if compare and not Path(compare).is_file():
            raise ValueError(f'Baseline not found: {compare}. Pull the repository baseline or specify --compare PATH')
        baseline = read_baseline(compare) if compare else None
        if compare:
            print(f'Baseline: {Path(compare).resolve()}', flush=True)
        print(f'Counting public tables (excluding temp/backup names) in database {config.db_name}.', flush=True)
        counts, captured_at = collect_counts()
        if not counts and baseline is None:
            raise ValueError('No included public tables found; baseline was not saved.')
        rows = report_rows(counts, captured_at, baseline)
        with output.open('x', encoding='utf-8-sig', newline='') as target:
            writer = csv.DictWriter(target, fieldnames=FIELDS)
            writer.writeheader()
            writer.writerows(rows)
    except (OSError, ValueError, psycopg2.Error) as exc:
        # Database exception text may contain connection details; do not print it.
        detail = str(exc) if isinstance(exc, ValueError) else type(exc).__name__
        print(f'ERROR: {detail}. No successful count verification. Check configuration, access, and file paths.')
        return 2

    print()
    for row in rows:
        count = f'{row["row_count"]:,}' if row['row_count'] is not None else 'missing'
        comparison = ''
        if baseline is not None:
            old = row['baseline_count']
            delta = row['difference']
            comparison = f' | baseline: {old:,}' if old is not None else ' | no baseline table'
            if delta is not None:
                comparison += f' | difference: {delta:+,}'
        print(f'[{row["status"]}] public.{row["table"]}: {count}{comparison}')
    failures = sum(row['status'] not in ('BASELINE', 'MATCH') for row in rows)
    print(f'\nReport saved: {output.resolve()}')
    if failures:
        print(f'FAIL: {failures} table(s) need review. Send the report to the DBA.')
        return 1
    if baseline is None:
        print(f'BASELINE SAVED: {len(rows)} tables. Share this CSV with the person checking AWS.')
    else:
        print(f'PASS: all {len(rows)} table counts match the baseline.')
    print('Equal counts do not prove identical row contents, schema, or permissions.')
    return 0
