import os
from pathlib import Path
import sys  
ROOT_PATH = Path(__file__).parent.parent.parent
sys.path.append(os.path.join(ROOT_PATH, ''))
from datetime import date
import ntpath

from python.util import utils, config
from python.util.dataset import Dataset 
from python.util.logger_factory import logger

# THIS SCRIPT DEAGGREGATES ENTIRE ROWS OF DATA THAT CONTAIN ROLLED UP DATA
# RUN SCRIPT deagg.py BEFORE THIS ONE TO DEAGGREGATE THE LOOKUP VALUES THEMSELVES. 
ust_or_release = 'ust'			# Valid values are 'ust' or 'release'
control_id = 0  	            # Enter an integer that is the ust_control_id or release_control_id
data_table_name = '' 			# Enter a string containing organization table name that contains the aggregated data 
data_table_pk_cols = [''] 		# Python list of column names FROM THE SOURCE DATA that the new table should be grouped by, for example, in UST, substances may be grouped by ['FacilityID','TankID'] or ['FacilityID','TankID','CompartmentID'] 
data_deagg_column_name = '' 	# Column name FROM THE SOURCE DATA that contains the aggregated values 
delimiters = [', '] 			# List of delimiters; defaults to [', ']. Put the most prevelant first. Put characters padded by spaces in list before those without spaces. Use '\n' for hard returns.
exclude_values = []			    # Python list. Values that contain the delimiter but should not be deaggregated
deagg_table_name = ''           # Deagg table name generated by deagg.py. It will begin with an 'erg_' prefix and end with a '_deagg' suffix. Check column deagg_table_name in table ust_element_mapping or release_element_mapping if you don't know it. (deagg.py will set this value.)
drop_existing = False 			# Boolean, defaults to False. Set to True to drop the _datarows_deagg table that this script creates before beginning (for example, if you need to rerun this script)


class deaggRows:
	conn = None  
	cur = None  
	cols = None 
	col_str = None 
	nonagged = 0

	def __init__(self, 
				 dataset,
				 data_table_name,
				 data_table_pk_cols,
				 data_deagg_column_name,
				 delimiters,
				 deagg_table_name,
				 exclude_values=None, 
				 drop_existing=False):
		self.dataset = dataset
		self.data_table_name = data_table_name
		self.data_table_pk_cols = data_table_pk_cols
		self.data_deagg_column_name = data_deagg_column_name
		self.delimiters = utils.string_to_list(delimiters)
		self.deagg_table_name = deagg_table_name
		self.exclude_values = exclude_values
		self.drop_existing = drop_existing
		self.data_deagg_table_name = utils.get_deagg_datarows_table_name(self.deagg_table_name)
		self.epa_table_name = self.deagg_table_name.replace('erg', self.dataset.ust_or_release).replace('_deagg','')
		self.element_mapping_table = self.dataset.ust_or_release + '_element_mapping'


	def connect_db(self):
		if not self.conn:
			self.conn = utils.connect_db()
			self.cur = self.conn.cursor()
			logger.info('Connected to database')


	def disconnect_db(self):
		if self.conn:
			self.conn.commit()
			self.cur.close()
			self.conn.close()
			self.conn = None 
			logger.info('Disconnected from database')


	def create_deagg_rows_table(self):
		sql = "select count(*) from information_schema.tables where table_schema = %s and table_name = %s"
		utils.process_sql(self.conn, self.cur, sql, params=(self.dataset.schema, self.data_deagg_table_name))
		cnt = self.cur.fetchone()[0]
		if cnt > 0:
			if self.drop_existing:
				sql2 = f'drop table {self.dataset.schema}."{self.data_deagg_table_name}"'
				utils.process_sql(self.conn, self.cur, sql2)
			else:
				logger.warning('Table %s.%s already exists but drop_existing flag is False. Set drop_existing to True to continue. Exiting...', self.dataset.schema, self.data_deagg_table_name)
				exit()

		# convert list of columns into a string and wrap each one in quotes 
		col_str = ''  
		for col in self.data_table_pk_cols:
			col_str = col_str + '"' + col + '",' 
		self.col_str = col_str
		
		# create _datarows_deagg table with empty column for deagged values 
		sql = f"""select {col_str} cast(null as varchar(400)) as "{self.data_deagg_column_name}" 
				  into {self.dataset.schema}."{self.data_deagg_table_name}" 
				  from {self.dataset.schema}."{self.data_table_name}" where 1=2""" 
		utils.process_sql(self.conn, self.cur, sql)
		logger.info('Created table %s.%s', self.dataset.schema, self.data_deagg_table_name)


	def get_cols(self):
		sql = """select column_name
				from information_schema.columns 
				where table_schema = %s and table_name = %s and column_name <> %s 
				order by ordinal_position"""
		utils.process_sql(self.conn, self.cur, sql, params=(self.dataset.schema, self.data_deagg_table_name, self.data_deagg_column_name))
		rows = self.cur.fetchall()
		cols = ['"' + r[0] + '"' for r in rows]
		return cols


	def get_col_str(self):
		if not self.cols:
			self.cols = self.get_cols()
		col_str = ''
		for col in self.cols:
			col_str += col + ','		
		return col_str


	def insert_nonagged(self):
		if not self.col_str:
			self.col_str = self.get_col_str()
		like_delimiters = ['%' + d + '%' for d in self.delimiters]
		sql = f"""insert into {self.dataset.schema}.{self.data_deagg_table_name} ({self.col_str} "{self.data_deagg_column_name}")  
				  select distinct {self.col_str} "{self.data_deagg_column_name}" from {self.dataset.schema}.{self.data_table_name}
				  where "{self.data_deagg_column_name}" is not null and "{self.data_deagg_column_name}" not like all(%s)
				  and not exists (select {self.col_str} "{self.data_deagg_column_name}" from {self.dataset.schema}.{self.data_deagg_table_name})"""
		utils.process_sql(self.conn, self.cur, sql, params=(like_delimiters,))
		self.nonagged = self.cur.rowcount
		logger.info('Inserted %s non-aggregated rows', self.nonagged)


	def deagg_rows(self, delimiter):
		logger.info('Working on delimiter "%s"', delimiter)
		if not self.cols:
			self.cols = self.get_cols()
		if not self.col_str:
			self.col_str = self.get_col_str()

		sql = f"""select distinct {self.col_str} "{self.data_deagg_column_name}" 
				  from {self.dataset.schema}."{self.data_table_name}" 
				  where "{self.data_deagg_column_name}" is not null and "{self.data_deagg_column_name}" like '%%{delimiter}%%'
		          and "{self.data_deagg_column_name}" <> any(%s)
				  order by 1, 2""" 
		utils.process_sql(self.conn, self.cur, sql, params=(self.exclude_values,))
		rows = self.cur.fetchall()
		n = 1
		for row in rows: 
			i = len(row)-1
			col_text = row[i]
			if col_text in self.exclude_values:
				logger.info('%s is in exclude_values, ignoring...', col_text)
				continue
			try:
				parts = col_text.split(delimiter)
			except AttributeError:
				continue
			for part in parts:
				part = part.strip()
				sql = f"""insert into {self.dataset.schema}.{self.data_deagg_table_name} ({self.col_str} "{self.data_deagg_column_name}") 
				          select """
				for r in row[:-1]:
					sql = sql + f" '{r}', "
				sql = sql + f""" '{part}'\nwhere not exists\n(select 1 from {self.dataset.schema}.{self.data_deagg_table_name}\nwhere """
				wheresql = ''
				for i in range(0, len(self.cols)):
					if row[i]:
						wheresql = wheresql + f" {self.cols[i]} = '{row[i]}' and "
					else:
						wheresql = wheresql + f" {self.cols[i]} is null and "
				wheresql = wheresql + f""" "{self.data_deagg_column_name}" = '{part}'"""
				sql = sql + wheresql + ')'
				utils.process_sql(self.conn, self.cur, sql)
				if self.cur.rowcount > 0:
					logger.info('Inserted %s into %s.%s', wheresql, self.dataset.schema, self.data_deagg_table_name)
				n += self.cur.rowcount
			self.conn.commit()

		logger.info('Finished deagging %s."%s"."%s" into %s; inserted %s rows', self.dataset.schema, self.data_table_name, self.data_deagg_column_name, self.data_deagg_table_name, n)
		self.conn.commit()

		if self.data_table_name == self.data_deagg_table_name:
			sql = f"""delete from {self.dataset.schema}.{self.data_table_name} 
					  where "{self.data_deagg_column_name}" like '%%{delimiter}%%' and "{self.data_deagg_column_name}" <> any(%s)"""
			utils.process_sql(self.conn, self.cur, sql, params=(self.exclude_values,))
			logger.info('Deleted %s existing rows in %s."%s"."%s" that contained the delimiter "%s"', self.cur.rowcount, self.dataset.schema, self.data_table_name, delimiter, self.exclude_values)


	def update_element_mapping(self):
		logger.info('Updating %s for %s', self.element_mapping_table, self.deagg_table_name)
		sql = f"""update public.{self.element_mapping_table} 
				  set deagg_table_name = %s
				  where {self.dataset.ust_or_release}_control_id = %s 
				  and deagg_table_name = %s"""
		utils.process_sql(self.conn, self.cur, sql, params=(self.data_deagg_table_name, self.dataset.control_id, self.deagg_table_name))
		self.conn.commit()
		logger.info('Updated element mapping for %s in %s', self.data_deagg_table_name, self.element_mapping_table)


	def process(self):
		self.connect_db()
		self.create_deagg_rows_table()
		self.insert_nonagged()
		delimiters = self.delimiters
		if self.nonagged == 0:
			self.deagg_rows(delimiters[0])
			delimiters.pop(0)
		for delimiter in delimiters:
			self.deagg_rows(delimiter)
		self.update_element_mapping()
		self.disconnect_db()


def deagg_only(ust_or_release,
		 control_id, 
		 data_table_name, 
		 data_table_pk_cols,
		 data_deagg_column_name,
		 deagg_table_name,
		 delimiters,
		 exclude_values,
		 drop_existing
		 ):
	dataset = Dataset(ust_or_release=ust_or_release,
					  control_id=control_id,
					  requires_export=False)
	drows = deaggRows(dataset=dataset, 
					 data_table_name=data_table_name, 
					 data_table_pk_cols=data_table_pk_cols,
					 data_deagg_column_name=data_deagg_column_name,
					 deagg_table_name=deagg_table_name,
					 delimiters=delimiters,
					 exclude_values=exclude_values, 
					 drop_existing=drop_existing)
	drows.connect_db()
	drows.deagg_rows()
	drows.disconnect_db()


def main(ust_or_release,
		 control_id, 
		 data_table_name, 
		 data_table_pk_cols,
		 data_deagg_column_name,
		 deagg_table_name,
		 delimiters,
		 exclude_values, 
		 drop_existing
		 ):
	dataset = Dataset(ust_or_release=ust_or_release,
					  control_id=control_id,
					  requires_export=False)
	drows = deaggRows(dataset=dataset, 
					 data_table_name=data_table_name, 
					 data_table_pk_cols=data_table_pk_cols,
					 data_deagg_column_name=data_deagg_column_name,
					 deagg_table_name=deagg_table_name,
					 delimiters=delimiters,
					 exclude_values=exclude_values,
					 drop_existing=drop_existing)
	drows.process()


if __name__ == '__main__':   
	main(ust_or_release=ust_or_release, 
		 control_id=control_id,
		 data_table_name=data_table_name, 
		 data_table_pk_cols=data_table_pk_cols,
		 data_deagg_column_name=data_deagg_column_name,
		 deagg_table_name=deagg_table_name,
		 delimiters=delimiters,
		 exclude_values=exclude_values,
		 drop_existing=drop_existing)
