
from ust.python.util import utils
from ust.python.util.dataset import Dataset
from ust.python.util.logger_factory import logger

ust_or_release = ''             # Valid values are 'ust' or 'release'
control_id = 0                     # Enter an integer that is the ust_control_id or release_control_id
organization_id = ''            # Optional; only used if control_id is not passed. If control_id == 0 or None, the script will retrieve the most recent control_id for the organization. 

# Set standalone_export to True to export the summaries genereated by this script to a standalone file. The default use of this
# script is to create additional worksheets to be included in the QAQC summary generated by qa_check.py; this occurs when
# standalone_export = False. 
standalone_export = False         
# These variables will be ignored if standalone_export = False. If True, they can usually be left unset. If standalone_export = True, 
# and the variables below are not set, this script will generate an Excel spreadsheet in the appropriate state folder in the repo 
# under /ust/python/exports/QAQC. This file directory and its contents are excluded from pushes to the repo by .gitignore.
export_file_path = None
export_file_dir = None
export_file_name = None


### 
# TODO: Standalone export not implemented
###

class Exclusions:
    def __init__(self, 
                 dataset,
                 standalone_export = False,
                 export_file_path = None,
                 export_file_dir = None,
                 export_file_name = None):
        self.dataset = dataset
        self.standalone_export = standalone_export
        self.export_file_path = export_file_path
        self.export_file_dir = export_file_dir
        self.export_file_name = export_file_name
        self.exclusions = {}
        self.process()


    def process(self):
        conn = utils.connect_db()
        cur = conn.cursor()

        if self.dataset.ust_or_release == 'release':
            unregulated_tables = ['erg_unregulated_releases', 'erg_unregulated_substances']
        else:
            unregulated_tables = ['erg_unregulated_facilities', 'erg_unregulated_tanks']

        sql = """select table_name from information_schema.tables 
                  where table_schema = %s and table_name = any(%s)
                  order by 1"""
        utils.process_sql(conn, cur, sql, params=(self.dataset.schema, unregulated_tables))
        rows = cur.fetchall()

        if len(rows) == 0:
            logger.info('No exclusion rows in dataset')
            cur.close()
            conn.close()
            return 

        for row in rows:
            table_name = row[0]
            pretty_name = table_name.replace('erg_','').replace('_', ' ').title()

            sql = """select column_name, ordinal_position
                      from information_schema.columns 
                      where table_schema = %s and table_name = %s
                      order by ordinal_position"""
            utils.process_sql(conn, cur, sql, params=(self.dataset.schema, table_name))
            rows2 = cur.fetchall()
            vsql = "select "
            headers = []
            for row2 in rows2:
                col_name = row2[0]
                if col_name == 'substance_id':
                    continue
                vsql += '"' + col_name + '", '
                headers.append(col_name)
            vsql = vsql[:-2]
            vsql += f"\nfrom {self.dataset.schema}.{table_name} order by 1"

            utils.process_sql(conn, cur, vsql, print_sql=True)
            rows = cur.fetchall()
            exclusion_metadata = {}
            exclusion_metadata['headers'] = headers
            exclusion_metadata['data'] = rows
            self.exclusions[pretty_name] = exclusion_metadata

        cur.close()
        conn.close()


    def print_self(self):
        for tab_name, metadata in self.exclusions.items():
            print(tab_name)
            print(str(metadata['headers']))
            for row in metadata['data']:
                print(row)
            print('\n\n')


def main(ust_or_release, 
         control_id=0, 
         organization_id=None, 
         standalone_export=False, 
         export_file_path=None, 
         export_file_dir=None,
         export_file_name=None):
    if not control_id or control_id == 0:
        control_id = utils.get_control_id(ust_or_release, organization_id.upper())

    dataset = Dataset(ust_or_release=ust_or_release,
                      control_id=control_id, 
                      base_file_name='QAQC_Exclusions_' + utils.get_timestamp_str() + '.xlsx',
                      export_file_name=export_file_name,
                      export_file_dir=export_file_dir,
                      export_file_path=export_file_path)

    s = Exclusions(dataset=dataset, standalone_export=standalone_export)
    s.print_self()


if __name__ == '__main__':   
    main(ust_or_release=ust_or_release,
         control_id=control_id, 
         organization_id=organization_id,
         standalone_export=standalone_export,
         export_file_name=export_file_name,
         export_file_dir=export_file_dir,
         export_file_path=export_file_path)
