
from ust.python.util import utils
from ust.python.util.dataset import Dataset
from ust.python.util.logger_factory import logger

ust_or_release = ''             # Valid values are 'ust' or 'release'
control_id = 0                  # Enter an integer that is the ust_control_id or release_control_id
organization_id = ''            # Optional; only used if control_id is not passed. If control_id == 0 or None, the script will retrieve the most recent control_id for the organization. 

# Set standalone_export to True to export the summaries genereated by this script to a standalone file. The default use of this
# script is to create additional worksheets to be included in the QAQC summary generated by qa_check.py; this occurs when
# standalone_export = False. 
standalone_export = False         
# These variables will be ignored if standalone_export = False. If True, they can usually be left unset. If standalone_export = True, 
# and the variables below are not set, this script will generate an Excel spreadsheet in the appropriate state folder in the repo 
# under /ust/python/exports/QAQC. This file directory and its contents are excluded from pushes to the repo by .gitignore.
export_file_path = None
export_file_dir = None
export_file_name = None


### 
# TODO: Standalone export not implemented
###

class SummaryCounts:
    conn = None 
    cur = None 

    def __init__(self, 
                 dataset,
                 standalone_export = False,
                 export_file_path = None,
                 export_file_dir = None,
                 export_file_name = None,
                 conn = None,
                 materialized_view_tables = None):
        self.dataset = dataset
        self.standalone_export = standalone_export
        self.export_file_path = export_file_path
        self.export_file_dir = export_file_dir
        self.export_file_name = export_file_name
        self.conn = conn
        self.owns_connection = conn is None
        self.materialized_view_tables = materialized_view_tables or {}
        self.summ_counts = {}
        self.connect_db()
        self.facility_type()
        self.tank_material()
        self.tank_status()
        self.compartment_status()
        self.piping_style()
        self.substance()
        self.disconnect_db()


    def connect_db(self):
        if not self.conn:
            self.conn = utils.connect_db()
            logger.info('Connected to database')
        self.cur = self.conn.cursor()


    def view_relation(self, view_name):
        temp_table = self.materialized_view_tables.get(view_name)
        if temp_table:
            return 'pg_temp."' + temp_table.replace('"', '""') + '"'
        return self.dataset.schema + '.' + view_name
        

    def disconnect_db(self):
        if self.cur:
            self.cur.close()
        if self.conn and self.owns_connection:
            self.conn.close()
            self.conn = None 
            logger.info('Disconnected from database')


    def facility_type(self):
        view_name = 'v_ust_'
        if self.dataset.ust_or_release == 'ust':
            view_name += 'facility'
        else:
            view_name += 'release'

        sql = """select column_name, count(*) 
                from information_schema.columns 
                where table_schema = %s
                and table_name = %s
                and column_name like 'facility_type%%'
                group by column_name order by column_name"""
        utils.process_sql(self.conn, self.cur, sql, params=(self.dataset.schema, view_name))
        rows = self.cur.fetchall()
        if not rows:
            return  
        if self.dataset.ust_or_release == 'ust' and len(rows) > 1:
            sql = f"""select facility_type, sum(cnt) as num_rows
                    from 
                        (select facility_type, count(*) as cnt
                        from {self.view_relation('v_ust_facility')} a join public.facility_types b on a.facility_type1 = b.facility_type_id
                        group by facility_type
                        union all 
                        select facility_type, count(*) as cnt
                        from {self.view_relation('v_ust_facility')} a join public.facility_types b on a.facility_type2 = b.facility_type_id
                        group by facility_type) x
                    group by facility_type order by facility_type"""
        else: 
            column_name = rows[0][0]
            sql = f"""select facility_type, count(*) as num_rows
                    from {self.view_relation(view_name)} a join public.facility_types b on a.{column_name} = b.facility_type_id
                    group by facility_type order by facility_type"""
        utils.process_sql(self.conn, self.cur, sql)
        rows = self.cur.fetchall()
        self.summ_counts['Facility Type Counts'] = rows


    def tank_material(self):
        if self.dataset.ust_or_release == 'release':
            return
        sql = f"""select tank_material_description, count(*) as num_rows
                from {self.view_relation('v_ust_tank')} a join public.tank_material_descriptions b
                    on a.tank_material_description_id = b.tank_material_description_id 
                group by tank_material_description order by tank_material_description"""
        utils.process_sql(self.conn, self.cur, sql)
        rows = self.cur.fetchall()
        self.summ_counts['Tank Material Counts'] = rows


    def tank_status(self):
        if self.dataset.ust_or_release == 'release':
            return
        sql = """select count(*) from information_schema.columns
                  where table_schema = %s 
                  and table_name = 'v_ust_tank'
                  and column_name = 'tank_status_id'"""
        utils.process_sql(self.conn, self.cur, sql, params=(self.dataset.schema,))
        cnt = self.cur.fetchone()[0]
        if cnt == 0:
            return
        sql = f"""select tank_status, count(*) as num_rows
                from {self.view_relation('v_ust_tank')} a join public.tank_statuses b
                    on a.tank_status_id = b.tank_status_id 
                group by tank_status order by tank_status"""
        utils.process_sql(self.conn, self.cur, sql)
        rows = self.cur.fetchall()
        self.summ_counts['Tank Status Counts'] = rows


    def compartment_status(self):
        if self.dataset.ust_or_release == 'release':
            return
        sql = """select count(*) from information_schema.columns
                  where table_schema = %s 
                  and table_name = 'v_ust_compartment'
                  and column_name = 'compartment_status_id'"""
        utils.process_sql(self.conn, self.cur, sql, params=(self.dataset.schema,))
        cnt = self.cur.fetchone()[0]
        if cnt == 0:
            return
        sql = f"""select compartment_status, count(*) as num_rows
                from {self.view_relation('v_ust_compartment')} a join public.compartment_statuses b
                    on a.compartment_status_id = b.compartment_status_id 
                group by compartment_status order by compartment_status"""
        utils.process_sql(self.conn, self.cur, sql)
        rows = self.cur.fetchall()
        self.summ_counts['Comp Status Counts'] = rows


    def piping_style(self):
        if self.dataset.ust_or_release == 'release':
            return
        sql = """select count(*) from information_schema.columns
                  where table_schema = %s 
                  and table_name = 'v_ust_piping'
                  and column_name = 'piping_style_id'"""
        utils.process_sql(self.conn, self.cur, sql, params=(self.dataset.schema,))
        cnt = self.cur.fetchone()[0]
        if cnt == 0:
            return
        sql = f"""select piping_style, count(*) as num_rows
                from {self.view_relation('v_ust_piping')} a join public.piping_styles b
                    on a.piping_style_id = b.piping_style_id 
                group by piping_style order by piping_style"""
        utils.process_sql(self.conn, self.cur, sql)
        rows = self.cur.fetchall()
        self.summ_counts['Piping Style Counts'] = rows


    def substance(self):
        view_name = ''
        view_found = True
        if self.dataset.ust_or_release == 'ust':
            sql = """select count(*) from information_schema.tables 
                      where table_schema = %s 
                      and table_name = 'v_ust_compartment_substance'"""
            utils.process_sql(self.conn, self.cur, sql, params=(self.dataset.schema,))
            cnt = self.cur.fetchone()[0]
            if cnt > 0:
                view_name = 'v_ust_compartment_substance'
            else:
                sql = """select count(*) from information_schema.tables 
                      where table_schema = %s 
                      and table_name = 'v_ust_tank_substance'"""
                utils.process_sql(self.conn, self.cur, sql, params=(self.dataset.schema,))
                cnt = self.cur.fetchone()[0]
                if cnt > 0:
                    view_name = 'v_ust_tank_substance'
                else:
                    view_found = False
        else:
            sql = """select count(*) from information_schema.tables 
                      where table_schema = %s 
                      and table_name = 'v_ust_release_substance'"""
            utils.process_sql(self.conn, self.cur, sql, params=(self.dataset.schema,))
            cnt = self.cur.fetchone()[0]
            if cnt > 0:
                view_name = 'v_ust_release_substance'
            else:
                view_found = False 
        if not view_found:
            return 

        sql = f"""select substance, count(*) as num_rows
                from {self.view_relation(view_name)} a join public.substances b
                    on a.substance_id = b.substance_id 
                group by substance order by substance"""
        utils.process_sql(self.conn, self.cur, sql)
        rows = self.cur.fetchall()
        self.summ_counts['Substance Counts'] = rows


    def print_self(self):
        for k, v in self.summ_counts.items():
            print(k)
            if v:
                for row in v:
                    print(row)
            print('\n\n')



def main(ust_or_release, 
         control_id=0, 
         organization_id=None, 
         standalone_export=False, 
         export_file_path=None, 
         export_file_dir=None,
         export_file_name=None):
    if not control_id or control_id == 0:
        control_id = utils.get_control_id(ust_or_release, organization_id)

    dataset = Dataset(ust_or_release=ust_or_release,
                      control_id=control_id, 
                      base_file_name='QAQC_Summary_Counts_' + utils.get_timestamp_str() + '.xlsx',
                      export_file_name=export_file_name,
                      export_file_dir=export_file_dir,
                      export_file_path=export_file_path)

    s = SummaryCounts(dataset=dataset, standalone_export=standalone_export)
    s.print_self()


if __name__ == '__main__':   
    main(ust_or_release=ust_or_release,
         control_id=control_id, 
         organization_id=organization_id,
         standalone_export=standalone_export,
         export_file_name=export_file_name,
         export_file_dir=export_file_dir,
         export_file_path=export_file_path)
