select '"' || element_name || '",' from ust_elements order by element_position ;

select * from "TRUSTD_UST"."TrUSTD_UST_template_20220714" ;

select * from ust_elements where element_name like '%Anode%';

update ust_elements set element_name = replace(element_name,'Anodes','Anode') where  element_name like '%Anode%';


create view "TRUSTD_UST".v_ust as
select
	"FacilityID",
	"FacilityName",
	"OwnerType",
	"FacilityType1",
	"FacilityType2",
	"FacilityAddress1",
	"FacilityAddress2",
	"FacilityCity",
	"FacilityCounty",
	"FacilityZipCode",
	"FacilityPhoneNumber",
	"FacilityState",
	null as "FacilityEPARegion",
	"FacilityTribe" as "FacilityTribalSite",
	"FacilityTribeName" as "FacilityTribe",
	"FacilityLatitude",
	"FacilityLongitude",
	"FacilityCoordinateSource",
	null as "FacilityOwnerCompanyName",
	"FacilityOwnerLastName",
	null as "FacilityOwnerFirstName",
	"FacilityOwnerAddress1",
	"FacilityOwnerAddress2",
	"FacilityOwnerCity",
	"FacilityOwnerCounty",
	"FacilityOwnerZipCode",
	"FacilityOwnerState",
	"FacilityOwnerPhoneNumber",
	null as "FacilityOwnerEmail",
	null as "FacilityOperatorCompanyName",
	"FacilityOperatorLastName",
	null as "FacilityOperatorFirstName",
	"FacilityOperatorAddress1",
	"FacilityOperatorAddress2",
	"FacilityOperatorCity",
	"FacilityOperatorCounty",
	"FacilityOperatorZipCode",
	"FacilityOperatorState",
	"FacilityOperatorPhoneNumber",
	null as "FacilityOperatorEmail",
	"FinancialResponsibilityBondRatingTest",
	"FinancialResponsibilityCommercialInsurance",
	"FinancialResponsibilityGuarantee",
	"FinancialResponsibilityLetterOfCredit",
	"FinancialResponsibilityLocalGovernmentFinancialTest",
	"FinancialResponsibilityRiskRetentionGroup",
	"FinancialResponsibilitySelfInsuranceFinancialTest",
	"FinancialResponsibilityStateFund",
	"FinancialResponsibilitySuretyBond",
	"FinancialResponsibilityTrustFund",
	"FinancialResponsibilityOtherMethod",
	"FinancialResponsibilityNotRequired",
	case when "FinancialResponsibilityBondRatingTest" is not null or 
		 "FinancialResponsibilityCommercialInsurance" is not null or 
		 "FinancialResponsibilityGuarantee" is not null or  
		 "FinancialResponsibilityLetterOfCredit" is not null or  
		 "FinancialResponsibilityLocalGovernmentFinancialTest" is not null or  
		 "FinancialResponsibilityRiskRetentionGroup" is not null or  
		 "FinancialResponsibilitySelfInsuranceFinancialTest" is not null or  
		 "FinancialResponsibilityStateFund" is not null or  
		 "FinancialResponsibilitySuretyBond" is not null or  
		 "FinancialResponsibilityTrustFund" is not null or   
		 "FinancialResponsibilityOtherMethod" is not null then 'Yes' end as "FinancialResponsibilityObtained",
	null as "Compliance",
	"TankID",
	null as "TankLocation",
	"FederallyRegulated",
	"TankStatus",
	null as "FieldConstructed",
	null as "EmergencyGenerator",
	null as "AirportHydrantSystem",
	"MultipleTanks",
	"ClosureDate",
	"InstallationDate",
	"CompartmentalizedUST",
	"NumberOfCompartments",
	"TankSubstanceStored",
	"CompartmentID",
	"CompartmentSubstanceStored",
	"TankCapacityGallons",
	"CompartmentCapacityGallons",
	null as "LinedTank",
	"ExcavationLiner",
	"TankWallType",
	"MaterialDescription",
	"TankRepaired",
	"TankRepairDate",
	null as "CertofInstallation",
	"PipingMaterialDescription",
	null as "PipingFlexConnector",
	"PipingStyle",
	"PipingWallType",
	null as "PipingUDCForEveryDispenser",
	"PipingRepaired",
	null as "PipingRepairDate",
	"TankCorrosionProtectionSacrificialAnode",
	null as "TankCorrosionProtectionAnodeInstalledOrRetrofitted",
	"TankCorrosionProtectionImpressedCurrent",
	null as "TankCorrosionProtectionImpressedCurrentInstalledOrRetrofitted",
	null as "TankCorrosionProtectionCathodicNotRequired",
	null as "TankCorrosionProtectionInteriorLining",
	null as "TankCorrosionProtectionOther",
	null as "TankCorrosionProtectionUnknown",
	null as "TankCorrosionProtectionLinedPostinstallation",
	"PipingCorrosionProtectionSacrificialAnode",
	null as "PipingCorrosionProtectionAnodeInstalledOrRetrofitted",
	"PipingCorrosionProtectionImpressedCurrent",
	null as "PipingCorrosionProtectionImpressedCurrentInstalledOrRetrofitted",
	null as "PipingCorrosionProtectionCathodicNotRequired",
	null as "PipingCorrosionProtectionExternalCoating",
	null as "PipingCorrosionProtectionOther",
	null as "PipingCorrosionProtectionUnknown",
	"BallFloatValve",
	"AutomaticShutoffDevice" as "FlowShutoffDevice",
	"OverfillAlarm" as "HighLevelAlarm",
	null as "OverfillProtectionPrimary",
	null as "OverfillProtectionSecondary",
	null as "PrimaryOverfillInstallDate",
	null as "SecondaryOverfillInstallDate",
	"SpillBucketInstalled",
	"SpillBucketWallType",
	null as "DrainPresent",
	null as "PumpPresent",
	null as "InterstitialMonitoringContinualElectric",
	null as "InterstitialMonitoringManual",
	"AutomaticTankGauging",
	null as "AutomaticTankGaugingReleaseDetection",
	null as "AutomaticTankGaugingContinuousLeakDetection",
	"ManualTankGauging",
	"StatisticalInventoryReconciliation",
	null as "TankTightnessTesting",
	"GroundwaterMonitoring",
	null as "SubpartK",
	"VaporMonitoring",
	null as "ElectronicLineLeak",
	null as "MechanicalLineLeak",
	null as "AutomatedIntersticialMonitoring",
	null as "SafeSuction",
	null as "AmericanSuction",
	null as "PipingSubpartK",
	null as "HighPressure",
	null as "PrimaryReleaseDetectionType",
	null as "SecondReleaseDetectionType",
	null as "PipeSecondaryContainment",
	null as "PipeInstallDate",
	"USTReportedRelease",
	"AssociatedLUSTID",
	null as "LastInspectionDate"
from "TRUSTD_UST"."TrUSTD_UST_template_20220714"; 


select * from "TRUSTD_UST".v_ust order by "FacilityID", "TankID";