select count(*) from "TrUSTD_UST_template_20220714" ;

delete from trustd_ust_template ;

select * from trustd_ust_template ;

alter table trustd_ust_template rename to geocode;

select * from public.ust_elements ;

select '"' || column_name || '",' 

from information_schema."columns" where table_schema = 'public' and table_name = 'ust' order by ordinal_position ;

create view v_ust_geocode as 
select 
a."FacilityID",
a."FacilityName",
"OwnerType",
"FacilityType1",
"FacilityType2",
"FacilityAddress1",
"FacilityAddress2",
"FacilityCity",
"FacilityCounty",
"FacilityZipCode",
"FacilityPhoneNumber",
"FacilityState",
null as "FacilityEPARegion",
"FacilityTribe" as "FacilityTribalSite",
"FacilityTribeName" as "FacilityTribe",
case when b.facilitylatitude  is not null then b.facilitylatitude else a."FacilityLatitude" end as "FacilityLatitude",
case when b.facilitylongitude  is not null then b.facilitylongitude else a."FacilityLongitude" end as "FacilityLongitude",
gc_coordinate_source,gc_address_type,
"FacilityCoordinateSource",
"FacilityOwnerLastName" as "FacilityOwnerCompanyName",
null as "FacilityOwnerLastName",
null as "FacilityOwnerFirstName",
"FacilityOwnerAddress1",
"FacilityOwnerAddress2",
"FacilityOwnerCity",
"FacilityOwnerCounty",
"FacilityOwnerZipCode",
"FacilityOwnerState",
"FacilityOwnerPhoneNumber",
null as "FacilityOwnerEmail",
"FacilityOperatorLastName" as "FacilityOperatorCompanyName",
null as "FacilityOperatorLastName",
null as "FacilityOperatorFirstName",
"FacilityOperatorAddress1",
"FacilityOperatorAddress2",
"FacilityOperatorCity",
"FacilityOperatorCounty",
"FacilityOperatorZipCode",
"FacilityOperatorState",
"FacilityOperatorPhoneNumber",
null as "FacilityOperatorEmail",
"FinancialResponsibilityBondRatingTest",
"FinancialResponsibilityCommercialInsurance",
"FinancialResponsibilityGuarantee",
"FinancialResponsibilityLetterOfCredit",
"FinancialResponsibilityLocalGovernmentFinancialTest",
"FinancialResponsibilityRiskRetentionGroup",
"FinancialResponsibilitySelfInsuranceFinancialTest",
"FinancialResponsibilityStateFund",
"FinancialResponsibilitySuretyBond",
"FinancialResponsibilityTrustFund",
"FinancialResponsibilityOtherMethod",
"FinancialResponsibilityNotRequired",
null as "FinancialResponsibilityObtained",
null as "Compliance",
"TankID",
null as "TankLocation",
"FederallyRegulated",
"TankStatus",
null as "FieldConstructed",
null as "EmergencyGenerator",
null as "AirportHydrantSystem",
"MultipleTanks",
"ClosureDate",
"InstallationDate",
"CompartmentalizedUST",
"NumberOfCompartments",
"TankSubstanceStored",
null as "CompartmentID",
"CompartmentSubstanceStored",
"TankCapacityGallons",
"CompartmentCapacityGallons",
null as "LinedTank",
"ExcavationLiner",
"TankWallType",
"MaterialDescription",
"TankRepaired",
"TankRepairDate",
null as "CertOfInstallation",
"PipingMaterialDescription",
null as "PipingFlexConnector",
"PipingStyle",
"PipingWallType",
null as "PipingUDC",
"PipingRepaired",
null as "PipingRepairDate",
"TankCorrosionProtectionSacrificialAnode",
null as "TankCorrosionProtectionAnodeInstalledOrRetrofitted",
"TankCorrosionProtectionImpressedCurrent",
null as "TankCorrosionProtectionImpressedCurrentInstalledOrRetrofitted",
null as "TankCorrosionProtectionCathodicNotRequired",
null as "TankCorrosionProtectionInteriorLining",
null as "TankCorrosionProtectionOther",
null as "TankCorrosionProtectionUnknown",
null as "TankCorrosionProtectionLinedPostinstallation",
"PipingCorrosionProtectionSacrificialAnode",
null as "PipingCorrosionProtectionAnodeInstalledOrRetrofitted",
"PipingCorrosionProtectionImpressedCurrent",
null as "PipingCorrosionProtectionImpressedCurrentInstalledOrRetrofitted",
null as "PipingCorrosionProtectionCathodicNotRequired",
null as "PipingCorrosionProtectionExternalCoating",
null as "PipingCorrosionProtectionOther",
null as "PipingCorrosionProtectionUnknown",
"BallFloatValve",
"AutomaticShutoffDevice" as "FlowShutoffDevice",
"OverfillAlarm" as "HighLevelAlarm",
null as "OverfillProtectionPrimary",
null as "OverfillProtectionSecondary",
null as "PrimaryOverfillInstallDate",
null as "SecondaryOverfillInstallDate",
"SpillBucketInstalled",
"SpillBucketWallType",
null as "DrainPresent",
null as "PumpPresent",
null as "InterstitialMonitoringContinualElectric",
null as "InterstitialMonitoringManual",
"AutomaticTankGauging",
null as "AutomaticTankGaugingReleaseDetection",
null as "AutomaticTankGaugingContinuousLeakDetection",
"ManualTankGauging",
"StatisticalInventoryReconciliation",
null as "TankTightnessTesting",
"GroundwaterMonitoring",
null as "SubpartK",
"VaporMonitoring",
null as "ElectronicLineLeak",
null as "MechanicalLineLeak",
null as "AutomatedIntersticialMonitoring",
null as "SafeSuction",
null as "AmericanSuction",
null as "PipingSubpartK",
null as "HighPressure",
null as "PrimaryReleaseDetectionType",
null as "SecondReleaseDetectionType",
null as "PipeSecondaryContainment",
null as "PipeInstallDate",
"USTReportedRelease",
"AssociatedLUSTID",
null as "LastInspectionDate"
from "TrUSTD_UST_template_20220714" a left join geocode b on a."FacilityID" = b.facilityid ;

select * from v_ust_geocode order by "FacilityID", "TankID";