select '"' || element_name || '",' from lust_elements order by element_position ;

select * from "TRUSTD_LUST"."TRUSTD_LUST_template_20220714";


create view "TRUSTD_LUST".v_lust as
select
	"FacilityID",
	"TankIDAssociatedwithRelease",
	"LUSTID",
	"FederallyReportableRelease",
	"SiteName",
	"SiteAddress",
	"SiteAddress2",
	"SiteCity",
	"Zipcode",
	"County",
	"State",
	"EPARegion",
	null as "FacilityType",
	"TribalSite",
	"TribeName" as "Tribe",
	"Latitude",
	"Longitude",
	"CoordinateSource",
	"LUSTStatus",
	"ReportedDate",
	"NFADate",
	"MediaImpactedSoil",
	"MediaImpactedGroundwater",
	"MediaImpactedSurfaceWater",
	"SubstanceReleased1",
	"QuantityReleased1",
	"Unit1",
	"SubstanceReleased2",
	"QuantityReleased2",
	"Unit2",
	"SubstanceReleased3",
	"AmountReleased3" as "QuantityReleased3",
	"Unit3",
	"SubstanceReleased4",
	"AmountReleased4" as "QuantityReleased4",
	"Unit4",
	"SubstanceReleased5",
	"AmountReleased5" as "QuantityReleased5",
	"Unit5",
	"SourceOfRelease1",
	"CauseOfRelease1",
	"SourceOfRelease2",
	"CauseOfRelease2",
	"SourceOfRelease3",
	"CauseOfRelease3",
	"HowReleaseDetected",
	"RemediationStrategy1",
	"RemediationStrategy1StartDate",
	"RemediationStrategy2",
	"RemediationStrategy2StartDate",
	"RemediationStrategy3",
	"RemediationStrategy3StartDate",
	"ClosedWithContamination",
	"NoFurtherActionLetterURL",
	"MilitaryDoDSite"
from "TRUSTD_LUST"."TrUSTD_LUST_template_20220714" ;

select * from "TRUSTD_LUST".v_lust order by "FacilityID", "LUSTID";