CREATE TABLE vt_ust.erg_vt_ust_clean_cui (
    "FacilityID" bigint  NULL ,
    "FacilityName" text  NULL ,
    "FacilityName_cui" boolean  NULL ,
    "OwnerType" text  NULL ,
    "FacilityType1" text  NULL ,
    "FacilityType2" double precision  NULL ,
    "FacilityAddress1" text  NULL ,
    "FacilityAddress2" double precision  NULL ,
    "FacilityCity" text  NULL ,
    "FacilityCounty" text  NULL ,
    "FacilityZipCode" text  NULL ,
    "FacilityState" text  NULL ,
    "FacilityEPARegion" bigint  NULL ,
    "FacilityTribalSite" double precision  NULL ,
    "FacilityTribe" double precision  NULL ,
    "FacilityLatitude" double precision  NULL ,
    "FacilityLongitude" double precision  NULL ,
    "FacilityCoordinateSource" text  NULL ,
    "FacilityOwnerCompanyName" text  NULL ,
    "FacilityOperatorCompanyName" text  NULL ,
    "FinancialResponsibility" text  NULL ,
    "FinancialResponsibilityObtained" text  NULL ,
    "FinancialResponsibilityBondRatingTest" text  NULL ,
    "FinancialResponsibilityCommercialInsurance" text  NULL ,
    "FinancialResponsibilityGuarantee" text  NULL ,
    "FinancialResponsibilityLetterOfCredit" text  NULL ,
    "FinancialResponsibilityLocalGovernmentFinancialTest" text  NULL ,
    "FinancialResponsibilityRiskRetentionGroup" text  NULL ,
    "FinancialResponsibilitySelfInsuranceFinancialTest" text  NULL ,
    "FinancialResponsibilityStateFund" text  NULL ,
    "FinancialResponsibilitySuretyBond" text  NULL ,
    "FinancialResponsibilityTrustFund" text  NULL ,
    "FinancialResponsibilityOtherMethod" double precision  NULL ,
    "USTReportedRelease" text  NULL ,
    "AssociatedLUSTID" double precision  NULL ,
    "DispenserID" text  NULL ,
    "DispenserUDC" text  NULL ,
    "DispenserUDCWallType" text  NULL );