select '"' || column_name || '",'
from information_schema.columns
where table_name = 'OR_LUST_template_20230113'
order by ordinal_position;

create view "OR_LUST".v_lust_base as 
select 
"FacilityID",
"TankIDAssociatedwithRelease",
"LUSTID",
"FederallyReportableRelease",
"SiteName",
"SiteAddress",
"SiteAddress2",
"SiteCity",
"Zipcode",
"County",
"State",
"EPARegion",
"FacilityType",
"TribalSite",
"Tribe",
"Latitude",
"Longitude",
"CoordinateSource",
"LUSTStatus",
"ReportedDate",
"NFADate",
"MediaImpactedSoil",
"MediaImpactedGroundwater",
"MediaImpactedSurfaceWater",
"SubstanceReleased1",
"QuantityReleased1",
"SubstanceReleased2",
"QuantityReleased2",
"SubstanceReleased3",
"QuantityReleased3",
"SubstanceReleased4",
"SubstanceReleased5",
"SourceOfRelease1",
"CauseOfRelease1",
"SourceofRelease2",
"CauseofRelease2",
"SourceofRelease3",
"CauseofRelease3",
"HowReleaseDetected",
"RemediationStrategy1",
"RemediationStrategyStartDate1",
"RemediationStrategy2",
"RemediationStrategyStartDate2",
"RemediationStrategy3",
"RemediationStrategyStartDate3",
"ClosedWithContamination",
"NoFurtherActionLetterURL",
"MilitaryDoDSite" 
from "OR_LUST"."OR_LUST_template_20230113";